import { pedagogyExamples } from "./pedagogy";

export type ExampleLocale = "es" | "en";

export type ExampleCategory =
  | "iterative"
  | "divide_and_conquer"
  | "decrease_and_conquer"
  | "decrease_and_get_conquered"
  | "dp_top_down"
  | "dp_bottom_up"
  | "greedy"
  | "backtracking"
  | "branch_and_bound";

export type RecursiveMethodBadge = "TM" | "IT" | "AR" | "EC";

export type TechniqueBadge =
  | "ITER"
  | "DyV"
  | "RyV"
  | "RySV"
  | "PD-TD"
  | "PD-BU"
  | "GREEDY"
  | "BT"
  | "B&B"
  | "FOR"
  | "WHILE"
  | "NESTED"
  | "FLAG"
  | "BACKSTEP"
  | "ACCUM"
  | "TABLE"
  | "MEMO"
  | "MATRIX"
  | "GRAPH"
  | "TREE"
  | "GRID"
  | "SORT"
  | "MERGE"
  | "PARTITION"
  | "BOUNDARY"
  | "SINGLE_BRANCH"
  | "MULTI_BRANCH"
  | "K_WAY"
  | "BOUND"
  | "PRUNE"
  | "UNDO"
  | "CHOICE"
  | "COMMIT"
  | "PRIORITY"
  | "OPTIMIZATION"
  | "INTERVAL"
  | "MST"
  | "SHORTEST_PATH"
  | "SCHEDULING"
  | "TILING"
  | "COUNTING"
  | "RATIO"
  | "N_MINUS_1"
  | "N_MINUS_K"
  | "INDEX_PLUS_1"
  | "TWO_POINTERS"
  | "INWARD"
  | "CLASSIC";

export type ExampleDifficulty = "basico" | "intermedio" | "avanzado";

export type CatalogTier = "contractual" | "experimental" | "blocked";

export type ExampleFamily =
  | "busqueda"
  | "ordenamiento"
  | "matrices"
  | "numerico"
  | "geometria"
  | "secuencias"
  | "estructuras"
  | "clasicos";

export interface ExampleCatalogCopy {
  title: string;
  summary: string;
  offText: string;
  tags: string[];
}

export interface ExampleCatalogItem {
  id: string;
  slug: string;
  category: ExampleCategory;
  family: ExampleFamily;
  difficulty: ExampleDifficulty;
  catalogTier: CatalogTier;
  sourceCodeByLocale: Record<ExampleLocale, string>;
  techniqueBadges: TechniqueBadge[];
  verifiedMethods: RecursiveMethodBadge[];
  enabled: boolean;
  copy: Record<ExampleLocale, ExampleCatalogCopy>;
}

export interface ExampleCategoryMeta {
  id: ExampleCategory;
  slug: string;
  titleKey: string;
  summaryKey: string;
  icon: string;
  pageIndex: 1 | 2 | 3;
}

export const EXAMPLE_CATEGORY_ORDER: ExampleCategory[] = [
  "iterative",
  "divide_and_conquer",
  "decrease_and_conquer",
  "decrease_and_get_conquered",
  "dp_top_down",
  "dp_bottom_up",
  "greedy",
  "backtracking",
  "branch_and_bound",
];

export const EXAMPLE_CATEGORY_SLUGS: Record<ExampleCategory, string> = {
  iterative: "iterative",
  divide_and_conquer: "divide-and-conquer",
  decrease_and_conquer: "decrease-and-conquer",
  decrease_and_get_conquered: "decrease-and-get-conquered",
  dp_top_down: "dp-top-down",
  dp_bottom_up: "dp-bottom-up",
  greedy: "greedy",
  backtracking: "backtracking",
  branch_and_bound: "branch-and-bound",
};

export const EXAMPLE_CATEGORY_META: Record<
  ExampleCategory,
  ExampleCategoryMeta
> = {
  iterative: {
    id: "iterative",
    slug: "iterative",
    titleKey: "examples.categories.iterative.title",
    summaryKey: "examples.categories.iterative.summary",
    icon: "sync_alt",
    pageIndex: 1,
  },
  divide_and_conquer: {
    id: "divide_and_conquer",
    slug: "divide-and-conquer",
    titleKey: "examples.categories.divideAndConquer.title",
    summaryKey: "examples.categories.divideAndConquer.summary",
    icon: "call_split",
    pageIndex: 1,
  },
  decrease_and_conquer: {
    id: "decrease_and_conquer",
    slug: "decrease-and-conquer",
    titleKey: "examples.categories.decreaseAndConquer.title",
    summaryKey: "examples.categories.decreaseAndConquer.summary",
    icon: "trending_down",
    pageIndex: 1,
  },
  decrease_and_get_conquered: {
    id: "decrease_and_get_conquered",
    slug: "decrease-and-get-conquered",
    titleKey: "examples.categories.decreaseAndGetConquered.title",
    summaryKey: "examples.categories.decreaseAndGetConquered.summary",
    icon: "account_tree",
    pageIndex: 2,
  },
  dp_top_down: {
    id: "dp_top_down",
    slug: "dp-top-down",
    titleKey: "examples.categories.dpTopDown.title",
    summaryKey: "examples.categories.dpTopDown.summary",
    icon: "vertical_align_top",
    pageIndex: 2,
  },
  dp_bottom_up: {
    id: "dp_bottom_up",
    slug: "dp-bottom-up",
    titleKey: "examples.categories.dpBottomUp.title",
    summaryKey: "examples.categories.dpBottomUp.summary",
    icon: "vertical_align_bottom",
    pageIndex: 2,
  },
  greedy: {
    id: "greedy",
    slug: "greedy",
    titleKey: "examples.categories.greedy.title",
    summaryKey: "examples.categories.greedy.summary",
    icon: "bolt",
    pageIndex: 3,
  },
  backtracking: {
    id: "backtracking",
    slug: "backtracking",
    titleKey: "examples.categories.backtracking.title",
    summaryKey: "examples.categories.backtracking.summary",
    icon: "undo",
    pageIndex: 3,
  },
  branch_and_bound: {
    id: "branch_and_bound",
    slug: "branch-and-bound",
    titleKey: "examples.categories.branchAndBound.title",
    summaryKey: "examples.categories.branchAndBound.summary",
    icon: "alt_route",
    pageIndex: 3,
  },
};

export const LEGACY_CATEGORY_REDIRECTS: Record<string, string> = {
  iterativos: "iterative",
  "divide-y-venceras": "divide-and-conquer",
  "resta-y-venceras": "decrease-and-conquer",
  "resta-y-seras-vencido": "decrease-and-get-conquered",
  "recursive-expansion": "decrease-and-get-conquered",
};

export const EXAMPLE_TECHNIQUES_PER_PAGE = 3;
export const EXAMPLE_CATEGORY_PAGE_COUNT = 3;

export const RECURSIVE_METHOD_BADGE_TO_METHOD = {
  TM: "master",
  IT: "iteration",
  AR: "recursion_tree",
  EC: "characteristic_equation",
} as const;

const EXAMPLE_METHOD_TRANSLATION_KEYS: Record<RecursiveMethodBadge, string> = {
  TM: "analyzer.methods.masterTheorem",
  IT: "analyzer.methods.iterationMethod",
  AR: "analyzer.methods.recursionTree",
  EC: "analyzer.methods.characteristicEquation",
};

export const EXAMPLE_FAMILY_ICONS: Record<ExampleFamily, string> = {
  busqueda: "travel_explore",
  ordenamiento: "swap_vert",
  matrices: "grid_view",
  numerico: "calculate",
  geometria: "pentagon",
  secuencias: "linear_scale",
  estructuras: "dataset",
  clasicos: "history_edu",
};

const code = (...lines: string[]): string => lines.join("\n");

const buildSourceCodeByLocale = (
  sourceCodeEs: string,
  sourceCodeEn?: string,
): Record<ExampleLocale, string> => ({
  es: sourceCodeEs,
  en: sourceCodeEn ?? sourceCodeEs,
});

const buildCopy = (
  _category: ExampleCategory,
  titleEs: string,
  titleEn: string,
  summaryEs: string,
  summaryEn: string,
  tagsEs: string[],
  tagsEn: string[],
): Record<ExampleLocale, ExampleCatalogCopy> => ({
  es: {
    title: titleEs,
    summary: summaryEs,
    offText: "",
    tags: tagsEs,
  },
  en: {
    title: titleEn,
    summary: summaryEn,
    offText: "",
    tags: tagsEn,
  },
});

const createExample = (
  item: Omit<
    ExampleCatalogItem,
    "copy" | "catalogTier" | "sourceCodeByLocale"
  > & {
    titleEs: string;
    titleEn: string;
    summaryEs: string;
    summaryEn: string;
    tagsEs: string[];
    tagsEn: string[];
    sourceCodeEs: string;
    sourceCodeEn?: string;
    catalogTier?: CatalogTier;
  },
): ExampleCatalogItem => ({
  id: item.id,
  slug: item.slug,
  category: item.category,
  family: item.family,
  difficulty: item.difficulty,
  catalogTier: item.catalogTier ?? "contractual",
  sourceCodeByLocale: buildSourceCodeByLocale(
    item.sourceCodeEs,
    item.sourceCodeEn,
  ),
  techniqueBadges: item.techniqueBadges,
  verifiedMethods: item.verifiedMethods,
  enabled: item.enabled,
  copy: buildCopy(
    item.category,
    item.titleEs,
    item.titleEn,
    item.summaryEs,
    item.summaryEn,
    item.tagsEs,
    item.tagsEn,
  ),
});

const iterativeExamples: ExampleCatalogItem[] = [
  createExample({
    id: "linear-search",
    slug: "linear-search",
    category: "iterative",
    family: "busqueda",
    difficulty: "basico",
    techniqueBadges: ["ITER", "FOR"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Búsqueda lineal",
    titleEn: "Linear Search",
    summaryEs: "Recorre el arreglo secuencialmente hasta encontrar la clave.",
    summaryEn: "Scans the array sequentially until it finds the key.",
    tagsEs: ["búsqueda", "for", "lineal"],
    tagsEn: ["search", "for", "linear"],
    sourceCodeEs: code(
      "linearSearch(A[n], n, x) BEGIN",
      "    FOR i <- 1 TO n DO BEGIN",
      "        IF (A[i] = x) THEN BEGIN",
      "            RETURN i;",
      "        END",
      "    END",
      "    RETURN -1;",
      "END",
    ),
    sourceCodeEn: code(
      "linearSearch(A[n], n, x) BEGIN",
      "    FOR i <- 1 TO n DO BEGIN",
      "        IF (A[i] = x) THEN BEGIN",
      "            RETURN i;",
      "        END",
      "    END",
      "    RETURN -1;",
      "END",
    ),
  }),
  createExample({
    id: "suma-de-arreglo",
    slug: "suma-de-arreglo",
    category: "iterative",
    family: "numerico",
    difficulty: "basico",
    techniqueBadges: ["ITER", "ACCUM"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Suma de arreglo",
    titleEn: "Array Sum",
    summaryEs: "Acumula todos los elementos del arreglo en una sola pasada.",
    summaryEn: "Accumulates all array elements in a single pass.",
    tagsEs: ["suma", "acumulador", "lineal"],
    tagsEn: ["sum", "accumulator", "linear"],
    sourceCodeEs: code(
      "sumaArreglo(A[n], n) BEGIN",
      "    suma <- 0;",
      "    FOR i <- 1 TO n DO BEGIN",
      "        suma <- suma + A[i];",
      "    END",
      "    RETURN suma;",
      "END",
    ),
  }),
  createExample({
    id: "bubble-sort",
    slug: "bubble-sort",
    category: "iterative",
    family: "ordenamiento",
    difficulty: "basico",
    techniqueBadges: ["ITER", "SORT", "NESTED"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Bubble Sort",
    titleEn: "Bubble Sort",
    summaryEs: "Ordena por intercambios adyacentes con doble bucle.",
    summaryEn: "Sorts by adjacent swaps with a double loop.",
    tagsEs: ["ordenamiento", "burbuja", "cuadrático"],
    tagsEn: ["sorting", "bubble", "quadratic"],
    sourceCodeEs: code(
      "bubbleSort(A[n], n) BEGIN",
      "    FOR i <- 1 TO n - 1 DO BEGIN",
      "        FOR j <- 1 TO n - i DO BEGIN",
      "            IF (A[j] > A[j + 1]) THEN BEGIN",
      "                temp <- A[j];",
      "                A[j] <- A[j + 1];",
      "                A[j + 1] <- temp;",
      "            END",
      "        END",
      "    END",
      "    RETURN 0;",
      "END",
    ),
  }),
  createExample({
    id: "bubble-sort-mejorado",
    slug: "bubble-sort-mejorado",
    category: "iterative",
    family: "ordenamiento",
    difficulty: "basico",
    techniqueBadges: ["ITER", "SORT", "FLAG"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Bubble Sort mejorado",
    titleEn: "Improved Bubble Sort",
    summaryEs: "Agrega una bandera para cortar temprano si ya está ordenado.",
    summaryEn: "Adds a flag to stop early when the array is already sorted.",
    tagsEs: ["ordenamiento", "bandera", "while"],
    tagsEn: ["sorting", "flag", "while"],
    sourceCodeEs: code(
      "bubbleSortMejorado(A[n], n) BEGIN",
      "    i <- 1;",
      "    WHILE (i <= n - 1) DO BEGIN",
      "        intercambio <- false;",
      "        FOR j <- 1 TO n - i DO BEGIN",
      "            IF (A[j] > A[j + 1]) THEN BEGIN",
      "                temp <- A[j];",
      "                A[j] <- A[j + 1];",
      "                A[j + 1] <- temp;",
      "                intercambio <- true;",
      "            END",
      "        END",
      "        IF (intercambio = false) THEN BEGIN",
      "            RETURN 0;",
      "        END",
      "        i <- i + 1;",
      "    END",
      "    RETURN 0;",
      "END",
    ),
  }),
  createExample({
    id: "gnome-sort",
    slug: "gnome-sort",
    category: "iterative",
    family: "ordenamiento",
    difficulty: "basico",
    techniqueBadges: ["ITER", "SORT", "BACKSTEP"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Gnome Sort",
    titleEn: "Gnome Sort",
    summaryEs: "Avanza o retrocede una posición según el orden local.",
    summaryEn:
      "Moves forward or backward one position depending on local order.",
    tagsEs: ["ordenamiento", "retroceso", "while"],
    tagsEn: ["sorting", "backstep", "while"],
    sourceCodeEs: code(
      "gnomeSort(A[n], n) BEGIN",
      "    i <- 2;",
      "    WHILE (i <= n) DO BEGIN",
      "        IF (i = 1) THEN BEGIN",
      "            i <- i + 1;",
      "        END",
      "        ELSE BEGIN",
      "            IF (A[i] >= A[i - 1]) THEN BEGIN",
      "                i <- i + 1;",
      "            END",
      "            ELSE BEGIN",
      "                temp <- A[i];",
      "                A[i] <- A[i - 1];",
      "                A[i - 1] <- temp;",
      "                i <- i - 1;",
      "            END",
      "        END",
      "    END",
      "    RETURN 0;",
      "END",
    ),
  }),
  createExample({
    id: "insertion-sort",
    slug: "insertion-sort",
    category: "iterative",
    family: "ordenamiento",
    difficulty: "basico",
    techniqueBadges: ["ITER", "SORT", "WHILE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Insertion Sort",
    titleEn: "Insertion Sort",
    summaryEs: "Inserta cada clave en el prefijo ya ordenado.",
    summaryEn: "Inserts each key into the already sorted prefix.",
    tagsEs: ["ordenamiento", "inserción", "while"],
    tagsEn: ["sorting", "insertion", "while"],
    sourceCodeEs: code(
      "insertionSort(A[n], n) BEGIN",
      "    FOR i <- 2 TO n DO BEGIN",
      "        clave <- A[i];",
      "        j <- i - 1;",
      "        WHILE (j > 0 AND A[j] > clave) DO BEGIN",
      "            A[j + 1] <- A[j];",
      "            j <- j - 1;",
      "        END",
      "        A[j + 1] <- clave;",
      "    END",
      "    RETURN 0;",
      "END",
    ),
  }),
  createExample({
    id: "euclides-iterativo-mcd",
    slug: "euclides-iterativo-mcd",
    category: "iterative",
    family: "numerico",
    difficulty: "basico",
    techniqueBadges: ["ITER", "WHILE", "CLASSIC"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Euclides iterativo",
    titleEn: "Iterative Euclid",
    summaryEs: "Calcula el MCD con una reducción iterativa por módulo.",
    summaryEn: "Computes the GCD with an iterative modulo reduction.",
    tagsEs: ["mcd", "mod", "clásico"],
    tagsEn: ["gcd", "mod", "classic"],
    sourceCodeEs: code(
      "euclidesIterativo(a, b) BEGIN",
      "    WHILE (b != 0) DO BEGIN",
      "        temp <- b;",
      "        b <- a MOD b;",
      "        a <- temp;",
      "    END",
      "    RETURN a;",
      "END",
    ),
  }),
  createExample({
    id: "sieve-of-eratosthenes",
    slug: "sieve-of-eratosthenes",
    category: "iterative",
    family: "numerico",
    difficulty: "intermedio",
    techniqueBadges: ["ITER", "TABLE", "COUNTING"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Criba de Eratóstenes",
    titleEn: "Sieve of Eratosthenes",
    summaryEs: "Marca múltiplos en una tabla booleana para hallar primos.",
    summaryEn: "Marks multiples in a boolean table to find primes.",
    tagsEs: ["criba", "primos", "tabla"],
    tagsEn: ["sieve", "primes", "table"],
    sourceCodeEs: code(
      "cribaEratostenes(n) BEGIN",
      "    FOR i <- 2 TO n DO BEGIN",
      "        primo[i] <- true;",
      "    END",
      "    FOR p <- 2 TO n DO BEGIN",
      "        IF (primo[p] = true) THEN BEGIN",
      "            multiplo <- p + p;",
      "            WHILE (multiplo <= n) DO BEGIN",
      "                primo[multiplo] <- false;",
      "                multiplo <- multiplo + p;",
      "            END",
      "        END",
      "    END",
      "    RETURN 0;",
      "END",
    ),
  }),
];

const divideAndConquerExamples: ExampleCatalogItem[] = [
  createExample({
    id: "binary-search-recursiva",
    slug: "binary-search-recursiva",
    category: "divide_and_conquer",
    family: "busqueda",
    difficulty: "basico",
    techniqueBadges: ["DyV", "SINGLE_BRANCH", "BOUNDARY"],
    verifiedMethods: ["TM"],
    enabled: true,
    titleEs: "Binary Search recursiva",
    titleEn: "Recursive Binary Search",
    summaryEs: "Parte el intervalo por la mitad y sigue una sola rama.",
    summaryEn: "Splits the interval in half and follows a single branch.",
    tagsEs: ["búsqueda", "mitad", "logarítmico"],
    tagsEn: ["search", "half", "logarithmic"],
    sourceCodeEs: code(
      "binarySearchRec(A[n], x, inicio, fin) BEGIN",
      "    IF (inicio > fin) THEN BEGIN",
      "        RETURN -1;",
      "    END",
      "    medio <- (inicio + fin) DIV 2;",
      "    IF (A[medio] = x) THEN BEGIN",
      "        RETURN medio;",
      "    END",
      "    IF (x < A[medio]) THEN BEGIN",
      "        RETURN binarySearchRec(A, x, inicio, medio - 1);",
      "    END",
      "    RETURN binarySearchRec(A, x, medio + 1, fin);",
      "END",
    ),
    sourceCodeEn: code(
      "recursiveBinarySearch(A[n], x, start, right) BEGIN",
      "    IF (start > right) THEN BEGIN",
      "        RETURN -1;",
      "    END",
      "    middle <- (start + right) DIV 2;",
      "    IF (A[middle] = x) THEN BEGIN",
      "        RETURN middle;",
      "    END",
      "    IF (x < A[middle]) THEN BEGIN",
      "        RETURN recursiveBinarySearch(A, x, start, middle - 1);",
      "    END",
      "    RETURN recursiveBinarySearch(A, x, middle + 1, right);",
      "END",
    ),
  }),
  createExample({
    id: "ternary-search-recursiva",
    slug: "ternary-search-recursiva",
    category: "divide_and_conquer",
    family: "busqueda",
    difficulty: "intermedio",
    techniqueBadges: ["DyV", "SINGLE_BRANCH", "K_WAY"],
    verifiedMethods: ["TM"],
    enabled: true,
    titleEs: "Ternary Search recursiva",
    titleEn: "Recursive Ternary Search",
    summaryEs: "Divide el intervalo en tres zonas y elige una.",
    summaryEn: "Divides the interval into three zones and chooses one.",
    tagsEs: ["búsqueda", "ternaria", "intervalo"],
    tagsEn: ["search", "ternary", "interval"],
    sourceCodeEs: code(
      "ternarySearchRec(A[n], x, inicio, fin) BEGIN",
      "    IF (inicio > fin) THEN BEGIN",
      "        RETURN -1;",
      "    END",
      "    tercio <- (fin - inicio) DIV 3;",
      "    m1 <- inicio + tercio;",
      "    m2 <- fin - tercio;",
      "    IF (A[m1] = x) THEN BEGIN",
      "        RETURN m1;",
      "    END",
      "    IF (A[m2] = x) THEN BEGIN",
      "        RETURN m2;",
      "    END",
      "    IF (x < A[m1]) THEN BEGIN",
      "        RETURN ternarySearchRec(A, x, inicio, m1 - 1);",
      "    END",
      "    IF (x > A[m2]) THEN BEGIN",
      "        RETURN ternarySearchRec(A, x, m2 + 1, fin);",
      "    END",
      "    RETURN ternarySearchRec(A, x, m1 + 1, m2 - 1);",
      "END",
    ),
  }),
  createExample({
    id: "merge-sort",
    slug: "merge-sort",
    category: "divide_and_conquer",
    family: "ordenamiento",
    difficulty: "intermedio",
    techniqueBadges: ["DyV", "MERGE", "PARTITION"],
    verifiedMethods: ["TM", "AR"],
    enabled: true,
    titleEs: "Merge Sort",
    titleEn: "Merge Sort",
    summaryEs: "Ordena mitades y luego las combina linealmente.",
    summaryEn: "Sorts both halves and then combines them linearly.",
    tagsEs: ["merge", "ordenamiento", "combinar"],
    tagsEn: ["merge", "sorting", "combine"],
    sourceCodeEs: code(
      "mergeSort(A[n], inicio, fin) BEGIN",
      "    IF (inicio < fin) THEN BEGIN",
      "        medio <- (inicio + fin) DIV 2;",
      "        CALL mergeSort(A, inicio, medio);",
      "        CALL mergeSort(A, medio + 1, fin);",
      "        CALL merge(A, inicio, medio, fin);",
      "    END",
      "    RETURN 0;",
      "END",
      "",
      "merge(A[n], inicio, medio, fin) BEGIN",
      "    i <- inicio;",
      "    j <- medio + 1;",
      "    k <- 1;",
      "    WHILE (i <= medio AND j <= fin) DO BEGIN",
      "        IF (A[i] <= A[j]) THEN BEGIN",
      "            temp[k] <- A[i];",
      "            i <- i + 1;",
      "        END",
      "        ELSE BEGIN",
      "            temp[k] <- A[j];",
      "            j <- j + 1;",
      "        END",
      "        k <- k + 1;",
      "    END",
      "    WHILE (i <= medio) DO BEGIN",
      "        temp[k] <- A[i];",
      "        i <- i + 1;",
      "        k <- k + 1;",
      "    END",
      "    WHILE (j <= fin) DO BEGIN",
      "        temp[k] <- A[j];",
      "        j <- j + 1;",
      "        k <- k + 1;",
      "    END",
      "    RETURN 0;",
      "END",
    ),
  }),
  createExample({
    id: "quick-sort",
    slug: "quick-sort",
    category: "divide_and_conquer",
    family: "ordenamiento",
    difficulty: "intermedio",
    techniqueBadges: ["DyV", "PARTITION", "SORT"],
    verifiedMethods: ["TM", "AR"],
    enabled: true,
    titleEs: "Quick Sort",
    titleEn: "Quick Sort",
    summaryEs: "Particiona por pivote y recursa sobre las regiones laterales.",
    summaryEn: "Partitions by pivot and recurses on the side regions.",
    tagsEs: ["quicksort", "pivote", "partición"],
    tagsEn: ["quicksort", "pivot", "partition"],
    sourceCodeEs: code(
      "quickSort(A[n], izq, der) BEGIN",
      "    IF (izq < der) THEN BEGIN",
      "        pivote <- A[der];",
      "        i <- izq - 1;",
      "        FOR j <- izq TO der - 1 DO BEGIN",
      "            IF (A[j] <= pivote) THEN BEGIN",
      "                i <- i + 1;",
      "                temp <- A[i];",
      "                A[i] <- A[j];",
      "                A[j] <- temp;",
      "            END",
      "        END",
      "        temp <- A[i + 1];",
      "        A[i + 1] <- A[der];",
      "        A[der] <- temp;",
      "        p <- i + 1;",
      "        CALL quickSort(A, izq, p - 1);",
      "        CALL quickSort(A, p + 1, der);",
      "    END",
      "    RETURN 0;",
      "END",
    ),
  }),
  createExample({
    id: "counting-inversions",
    slug: "counting-inversions",
    category: "divide_and_conquer",
    family: "ordenamiento",
    difficulty: "intermedio",
    techniqueBadges: ["DyV", "MERGE", "COUNTING"],
    verifiedMethods: ["TM", "AR"],
    enabled: true,
    titleEs: "Counting Inversions",
    titleEn: "Counting Inversions",
    summaryEs: "Cuenta inversiones por mitades y cruces.",
    summaryEn: "Counts inversions by halves and crossings.",
    tagsEs: ["inversiones", "merge", "conteo"],
    tagsEn: ["inversions", "merge", "counting"],
    sourceCodeEs: code(
      "countInversions(A[n], inicio, fin) BEGIN",
      "    IF (inicio >= fin) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    medio <- (inicio + fin) DIV 2;",
      "    izquierda <- countInversions(A, inicio, medio);",
      "    derecha <- countInversions(A, medio + 1, fin);",
      "    cruzadas <- mergeAndCount(A, inicio, medio, fin);",
      "    RETURN izquierda + derecha + cruzadas;",
      "END",
      "",
      "mergeAndCount(A[n], inicio, medio, fin) BEGIN",
      "    i <- inicio;",
      "    j <- medio + 1;",
      "    total <- 0;",
      "    WHILE (i <= medio AND j <= fin) DO BEGIN",
      "        IF (A[i] <= A[j]) THEN BEGIN",
      "            i <- i + 1;",
      "        END",
      "        ELSE BEGIN",
      "            total <- total + medio - i + 1;",
      "            j <- j + 1;",
      "        END",
      "    END",
      "    RETURN total;",
      "END",
    ),
  }),
  createExample({
    id: "maximum-subarray-divide-and-conquer",
    slug: "maximum-subarray-divide-and-conquer",
    category: "divide_and_conquer",
    family: "numerico",
    difficulty: "intermedio",
    techniqueBadges: ["DyV", "MERGE", "INTERVAL"],
    verifiedMethods: ["TM", "AR"],
    enabled: true,
    titleEs: "Maximum Subarray DyV",
    titleEn: "Maximum Subarray D&C",
    summaryEs: "Compara mejor subarreglo izquierdo, derecho y cruzado.",
    summaryEn: "Compares the best left, right, and crossing subarray.",
    tagsEs: ["subarreglo", "cruzado", "intervalo"],
    tagsEn: ["subarray", "crossing", "interval"],
    sourceCodeEs: code(
      "maxSubarrayDC(A[n], inicio, fin) BEGIN",
      "    IF (inicio = fin) THEN BEGIN",
      "        RETURN A[inicio];",
      "    END",
      "    medio <- (inicio + fin) DIV 2;",
      "    izq <- maxSubarrayDC(A, inicio, medio);",
      "    der <- maxSubarrayDC(A, medio + 1, fin);",
      "    cruz <- maxSubarrayCruzando(A, inicio, medio, fin);",
      "    IF (izq >= der AND izq >= cruz) THEN BEGIN",
      "        RETURN izq;",
      "    END",
      "    IF (der >= cruz) THEN BEGIN",
      "        RETURN der;",
      "    END",
      "    RETURN cruz;",
      "END",
      "",
      "maxSubarrayCruzando(A[n], inicio, medio, fin) BEGIN",
      "    suma <- 0;",
      "    mejorIzq <- A[medio];",
      "    i <- medio;",
      "    WHILE (i >= inicio) DO BEGIN",
      "        suma <- suma + A[i];",
      "        IF (suma > mejorIzq) THEN BEGIN",
      "            mejorIzq <- suma;",
      "        END",
      "        i <- i - 1;",
      "    END",
      "    suma <- 0;",
      "    mejorDer <- A[medio + 1];",
      "    j <- medio + 1;",
      "    WHILE (j <= fin) DO BEGIN",
      "        suma <- suma + A[j];",
      "        IF (suma > mejorDer) THEN BEGIN",
      "            mejorDer <- suma;",
      "        END",
      "        j <- j + 1;",
      "    END",
      "    RETURN mejorIzq + mejorDer;",
      "END",
    ),
  }),
  createExample({
    id: "strassen-matrix-multiplication",
    slug: "strassen-matrix-multiplication",
    category: "divide_and_conquer",
    family: "matrices",
    difficulty: "avanzado",
    techniqueBadges: ["DyV", "MATRIX", "K_WAY"],
    verifiedMethods: ["TM"],
    enabled: true,
    titleEs: "Strassen Matrix Multiplication",
    titleEn: "Strassen Matrix Multiplication",
    summaryEs: "Modelo simplificado de 7 subproductos recursivos.",
    summaryEn: "Simplified model with 7 recursive subproducts.",
    tagsEs: ["strassen", "matrices", "7 productos"],
    tagsEn: ["strassen", "matrices", "7 products"],
    catalogTier: "blocked",
    sourceCodeEs: code(
      "strassen(A[n][n], B[n][n], n) BEGIN",
      "    IF (n = 1) THEN BEGIN",
      "        RETURN A[1][1] * B[1][1];",
      "    END",
      "    mitad <- n DIV 2;",
      "    p1 <- strassen(A, B, mitad);",
      "    p2 <- strassen(A, B, mitad);",
      "    p3 <- strassen(A, B, mitad);",
      "    p4 <- strassen(A, B, mitad);",
      "    p5 <- strassen(A, B, mitad);",
      "    p6 <- strassen(A, B, mitad);",
      "    p7 <- strassen(A, B, mitad);",
      "    RETURN p1 + p2 + p3 + p4 + p5 + p6 + p7;",
      "END",
    ),
  }),
  createExample({
    id: "z-order-recursive-matrix-traversal",
    slug: "z-order-recursive-matrix-traversal",
    category: "divide_and_conquer",
    family: "matrices",
    difficulty: "intermedio",
    techniqueBadges: ["DyV", "MATRIX", "GRID"],
    verifiedMethods: ["TM"],
    enabled: true,
    titleEs: "Z-order Matrix Traversal",
    titleEn: "Z-order Matrix Traversal",
    summaryEs: "Recorre cuadrantes en orden Z.",
    summaryEn: "Traverses quadrants in Z order.",
    tagsEs: ["matriz", "cuadrantes", "z-order"],
    tagsEn: ["matrix", "quadrants", "z-order"],
    sourceCodeEs: code(
      "zOrder(M[n][n], fila, col, tam) BEGIN",
      "    IF (tam = 1) THEN BEGIN",
      "        RETURN M[fila][col];",
      "    END",
      "    mitad <- tam DIV 2;",
      "    q1 <- zOrder(M, fila, col, mitad);",
      "    q2 <- zOrder(M, fila, col + mitad, mitad);",
      "    q3 <- zOrder(M, fila + mitad, col, mitad);",
      "    q4 <- zOrder(M, fila + mitad, col + mitad, mitad);",
      "    RETURN q1 + q2 + q3 + q4;",
      "END",
    ),
  }),
];

const decreaseAndConquerExamples: ExampleCatalogItem[] = [
  createExample({
    id: "factorial-recursivo",
    slug: "factorial-recursivo",
    category: "decrease_and_conquer",
    family: "numerico",
    difficulty: "basico",
    techniqueBadges: ["RyV", "N_MINUS_1", "SINGLE_BRANCH"],
    verifiedMethods: ["IT"],
    enabled: true,
    titleEs: "Factorial recursivo",
    titleEn: "Recursive Factorial",
    summaryEs: "Reduce n en una unidad por llamada.",
    summaryEn: "Reduces n by one on each call.",
    tagsEs: ["factorial", "n-1", "recursión"],
    tagsEn: ["factorial", "n-1", "recursion"],
    sourceCodeEs: code(
      "factorialRecursivo(n) BEGIN",
      "    IF (n <= 1) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    RETURN n * factorialRecursivo(n - 1);",
      "END",
    ),
  }),
  createExample({
    id: "potencia-recursiva-naive",
    slug: "potencia-recursiva-naive",
    category: "decrease_and_conquer",
    family: "numerico",
    difficulty: "basico",
    techniqueBadges: ["RyV", "N_MINUS_1", "SINGLE_BRANCH"],
    verifiedMethods: ["IT"],
    enabled: true,
    titleEs: "Potencia recursiva naïve",
    titleEn: "Naive Recursive Power",
    summaryEs: "Reduce el exponente en una unidad.",
    summaryEn: "Reduces the exponent by one.",
    tagsEs: ["potencia", "n-1", "lineal"],
    tagsEn: ["power", "n-1", "linear"],
    sourceCodeEs: code(
      "potenciaNaive(x, n) BEGIN",
      "    IF (n = 0) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    RETURN x * potenciaNaive(x, n - 1);",
      "END",
    ),
  }),
  createExample({
    id: "suma-de-1-a-n-recursiva",
    slug: "suma-de-1-a-n-recursiva",
    category: "decrease_and_conquer",
    family: "numerico",
    difficulty: "basico",
    techniqueBadges: ["RyV", "N_MINUS_1", "ACCUM"],
    verifiedMethods: ["IT"],
    enabled: true,
    titleEs: "Suma de 1 a n recursiva",
    titleEn: "Recursive Sum 1..n",
    summaryEs: "Acumula el valor actual y llama con n - 1.",
    summaryEn: "Accumulates the current value and calls with n - 1.",
    tagsEs: ["suma", "n-1", "lineal"],
    tagsEn: ["sum", "n-1", "linear"],
    sourceCodeEs: code(
      "sumaUnoAN(n) BEGIN",
      "    IF (n <= 1) THEN BEGIN",
      "        RETURN n;",
      "    END",
      "    RETURN n + sumaUnoAN(n - 1);",
      "END",
    ),
  }),
  createExample({
    id: "suma-de-arreglo-recursiva",
    slug: "suma-de-arreglo-recursiva",
    category: "decrease_and_conquer",
    family: "numerico",
    difficulty: "basico",
    techniqueBadges: ["RyV", "N_MINUS_1", "ACCUM"],
    verifiedMethods: ["IT"],
    enabled: true,
    titleEs: "Suma de arreglo recursiva",
    titleEn: "Recursive Array Sum",
    summaryEs: "Consume un elemento por llamada.",
    summaryEn: "Consumes one element per call.",
    tagsEs: ["arreglo", "suma", "n-1"],
    tagsEn: ["array", "sum", "n-1"],
    sourceCodeEs: code(
      "sumaArregloRec(A[n], n) BEGIN",
      "    IF (n = 0) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    RETURN A[n] + sumaArregloRec(A, n - 1);",
      "END",
    ),
  }),
  createExample({
    id: "linear-search-recursiva",
    slug: "linear-search-recursiva",
    category: "decrease_and_conquer",
    family: "busqueda",
    difficulty: "basico",
    techniqueBadges: ["RyV", "INDEX_PLUS_1", "SINGLE_BRANCH"],
    verifiedMethods: ["IT"],
    enabled: true,
    titleEs: "Linear Search recursiva",
    titleEn: "Recursive Linear Search",
    summaryEs: "Avanza el índice en una unidad por llamada.",
    summaryEn: "Advances the index by one per call.",
    tagsEs: ["búsqueda", "índice", "i+1"],
    tagsEn: ["search", "index", "i+1"],
    sourceCodeEs: code(
      "linearSearchRec(A[n], x, i, n) BEGIN",
      "    IF (i > n) THEN BEGIN",
      "        RETURN -1;",
      "    END",
      "    IF (A[i] = x) THEN BEGIN",
      "        RETURN i;",
      "    END",
      "    RETURN linearSearchRec(A, x, i + 1, n);",
      "END",
    ),
  }),
  createExample({
    id: "find-maximum-recursivo",
    slug: "find-maximum-recursivo",
    category: "decrease_and_conquer",
    family: "numerico",
    difficulty: "basico",
    techniqueBadges: ["RyV", "N_MINUS_1", "SINGLE_BRANCH"],
    verifiedMethods: ["IT"],
    enabled: true,
    titleEs: "Find Maximum recursivo",
    titleEn: "Recursive Find Maximum",
    summaryEs: "Compara el último elemento con el máximo del prefijo.",
    summaryEn: "Compares the last element with the prefix maximum.",
    tagsEs: ["máximo", "prefijo", "n-1"],
    tagsEn: ["maximum", "prefix", "n-1"],
    sourceCodeEs: code(
      "findMaximumRec(A[n], n) BEGIN",
      "    IF (n = 1) THEN BEGIN",
      "        RETURN A[1];",
      "    END",
      "    anterior <- findMaximumRec(A, n - 1);",
      "    IF (A[n] > anterior) THEN BEGIN",
      "        RETURN A[n];",
      "    END",
      "    RETURN anterior;",
      "END",
    ),
  }),
  createExample({
    id: "insertion-sort-recursivo",
    slug: "insertion-sort-recursivo",
    category: "decrease_and_conquer",
    family: "ordenamiento",
    difficulty: "intermedio",
    techniqueBadges: ["RyV", "SORT", "N_MINUS_1"],
    verifiedMethods: ["IT"],
    enabled: true,
    titleEs: "Insertion Sort recursivo",
    titleEn: "Recursive Insertion Sort",
    summaryEs: "Ordena n - 1 elementos e inserta el último.",
    summaryEn: "Sorts n - 1 elements and inserts the last one.",
    tagsEs: ["ordenamiento", "inserción", "n-1"],
    tagsEn: ["sorting", "insertion", "n-1"],
    sourceCodeEs: code(
      "insertionSortRec(A[n], n) BEGIN",
      "    IF (n <= 1) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    CALL insertionSortRec(A, n - 1);",
      "    clave <- A[n];",
      "    j <- n - 1;",
      "    WHILE (j > 0 AND A[j] > clave) DO BEGIN",
      "        A[j + 1] <- A[j];",
      "        j <- j - 1;",
      "    END",
      "    A[j + 1] <- clave;",
      "    RETURN 0;",
      "END",
    ),
  }),
  createExample({
    id: "palindrome-check-recursivo",
    slug: "palindrome-check-recursivo",
    category: "decrease_and_conquer",
    family: "estructuras",
    difficulty: "basico",
    techniqueBadges: ["RyV", "TWO_POINTERS", "INWARD"],
    verifiedMethods: ["IT"],
    enabled: true,
    titleEs: "Palindrome Check recursivo",
    titleEn: "Recursive Palindrome Check",
    summaryEs: "Reduce el intervalo desde ambos extremos.",
    summaryEn: "Shrinks the interval from both ends.",
    tagsEs: ["palíndromo", "dos punteros", "centro"],
    tagsEn: ["palindrome", "two pointers", "center"],
    sourceCodeEs: code(
      "palindromeRec(S[n], izq, der) BEGIN",
      "    IF (izq >= der) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    IF (S[izq] != S[der]) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    RETURN palindromeRec(S, izq + 1, der - 1);",
      "END",
    ),
  }),
];

const decreaseAndGetConqueredExamples: ExampleCatalogItem[] = [
  createExample({
    id: "fibonacci-recursivo",
    slug: "fibonacci-recursivo",
    category: "decrease_and_get_conquered",
    family: "secuencias",
    difficulty: "basico",
    techniqueBadges: ["RySV", "MULTI_BRANCH", "CLASSIC"],
    verifiedMethods: ["EC"],
    enabled: true,
    titleEs: "Fibonacci recursivo",
    titleEn: "Recursive Fibonacci",
    summaryEs: "Abre dos ramas con reducción aditiva.",
    summaryEn: "Opens two branches with additive shrink.",
    tagsEs: ["fibonacci", "dos ramas", "ec"],
    tagsEn: ["fibonacci", "two branches", "ce"],
    sourceCodeEs: code(
      "fibonacci(n) BEGIN",
      "    IF (n <= 1) THEN BEGIN",
      "        RETURN n;",
      "    END",
      "    RETURN fibonacci(n - 1) + fibonacci(n - 2);",
      "END",
    ),
  }),
  createExample({
    id: "tribonacci-recursivo",
    slug: "tribonacci-recursivo",
    category: "decrease_and_get_conquered",
    family: "secuencias",
    difficulty: "intermedio",
    techniqueBadges: ["RySV", "MULTI_BRANCH", "COUNTING"],
    verifiedMethods: ["EC"],
    enabled: true,
    titleEs: "Tribonacci recursivo",
    titleEn: "Recursive Tribonacci",
    summaryEs: "Abre tres ramas sobre n - 1, n - 2 y n - 3.",
    summaryEn: "Opens three branches on n - 1, n - 2, and n - 3.",
    tagsEs: ["tribonacci", "tres ramas", "ec"],
    tagsEn: ["tribonacci", "three branches", "ce"],
    sourceCodeEs: code(
      "tribonacci(n) BEGIN",
      "    IF (n <= 1) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    IF (n = 2) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    RETURN tribonacci(n - 1) + tribonacci(n - 2) + tribonacci(n - 3);",
      "END",
    ),
  }),
  createExample({
    id: "tetranacci-sequence",
    slug: "tetranacci-sequence",
    category: "decrease_and_get_conquered",
    family: "secuencias",
    difficulty: "intermedio",
    techniqueBadges: ["RySV", "MULTI_BRANCH", "COUNTING"],
    verifiedMethods: ["EC"],
    enabled: true,
    titleEs: "Tetranacci",
    titleEn: "Tetranacci Sequence",
    summaryEs: "Extiende el patrón a cuatro ramas.",
    summaryEn: "Extends the pattern to four branches.",
    tagsEs: ["tetranacci", "cuatro ramas", "ec"],
    tagsEn: ["tetranacci", "four branches", "ce"],
    sourceCodeEs: code(
      "tetranacci(n) BEGIN",
      "    IF (n <= 2) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    IF (n = 3) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    RETURN tetranacci(n - 1) + tetranacci(n - 2) + tetranacci(n - 3) + tetranacci(n - 4);",
      "END",
    ),
  }),
  createExample({
    id: "hanoi",
    slug: "hanoi",
    category: "decrease_and_get_conquered",
    family: "clasicos",
    difficulty: "basico",
    techniqueBadges: ["RySV", "MULTI_BRANCH", "CLASSIC"],
    verifiedMethods: ["EC"],
    enabled: true,
    titleEs: "Torres de Hanoi",
    titleEn: "Tower of Hanoi",
    summaryEs: "Hace dos llamadas sobre n - 1 y combina un movimiento central.",
    summaryEn: "Makes two calls on n - 1 and combines a central move.",
    tagsEs: ["hanoi", "clásico", "dos ramas"],
    tagsEn: ["hanoi", "classic", "two branches"],
    sourceCodeEs: code(
      "hanoi(n, origen, destino, auxiliar) BEGIN",
      "    IF (n = 1) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    izquierda <- hanoi(n - 1, origen, auxiliar, destino);",
      "    derecha <- hanoi(n - 1, auxiliar, destino, origen);",
      "    RETURN izquierda + derecha + 1;",
      "END",
    ),
  }),
  createExample({
    id: "climbing-stairs",
    slug: "climbing-stairs",
    category: "decrease_and_get_conquered",
    family: "secuencias",
    difficulty: "basico",
    techniqueBadges: ["RySV", "MULTI_BRANCH", "COUNTING"],
    verifiedMethods: ["EC"],
    enabled: true,
    titleEs: "Escaleras recursivas",
    titleEn: "Climbing Stairs",
    summaryEs: "Cuenta formas de subir con pasos 1 o 2.",
    summaryEn: "Counts ways to climb using steps of 1 or 2.",
    tagsEs: ["escaleras", "fibonacci", "conteo"],
    tagsEn: ["stairs", "fibonacci", "counting"],
    sourceCodeEs: code(
      "escaleras(n) BEGIN",
      "    IF (n <= 1) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    RETURN escaleras(n - 1) + escaleras(n - 2);",
      "END",
    ),
  }),
  createExample({
    id: "frog-jump-1-2-3",
    slug: "frog-jump-1-2-3",
    category: "decrease_and_get_conquered",
    family: "secuencias",
    difficulty: "intermedio",
    techniqueBadges: ["RySV", "MULTI_BRANCH", "COUNTING"],
    verifiedMethods: ["EC"],
    enabled: true,
    titleEs: "Rana 1-2-3",
    titleEn: "Frog Jump 1-2-3",
    summaryEs: "Cuenta caminos con saltos de 1, 2 o 3.",
    summaryEn: "Counts paths with jumps of 1, 2, or 3.",
    tagsEs: ["rana", "saltos", "tribonacci"],
    tagsEn: ["frog", "jumps", "tribonacci"],
    sourceCodeEs: code(
      "ranaSaltos123(n) BEGIN",
      "    IF (n < 0) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    IF (n = 0) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    RETURN ranaSaltos123(n - 1) + ranaSaltos123(n - 2) + ranaSaltos123(n - 3);",
      "END",
    ),
  }),
  createExample({
    id: "count-binary-strings-without-consecutive-ones",
    slug: "count-binary-strings-without-consecutive-ones",
    category: "decrease_and_get_conquered",
    family: "secuencias",
    difficulty: "intermedio",
    techniqueBadges: ["RySV", "MULTI_BRANCH", "COUNTING"],
    verifiedMethods: ["EC"],
    enabled: true,
    titleEs: "Cadenas binarias sin unos consecutivos",
    titleEn: "Count Binary Strings Without Consecutive Ones",
    summaryEs: "Cuenta cadenas binarias válidas con dos ramas.",
    summaryEn: "Counts valid binary strings with two branches.",
    tagsEs: ["binarias", "fibonacci", "conteo"],
    tagsEn: ["binary", "fibonacci", "counting"],
    sourceCodeEs: code(
      "countBinaryStringsOnes(n) BEGIN",
      "    IF (n <= 1) THEN BEGIN",
      "        RETURN 2;",
      "    END",
      "    RETURN countBinaryStringsOnes(n - 1) + countBinaryStringsOnes(n - 2);",
      "END",
    ),
  }),
  createExample({
    id: "ways-to-tile-2xn",
    slug: "ways-to-tile-2xn",
    category: "decrease_and_get_conquered",
    family: "secuencias",
    difficulty: "intermedio",
    techniqueBadges: ["RySV", "MULTI_BRANCH", "TILING"],
    verifiedMethods: ["EC"],
    enabled: true,
    titleEs: "Formas de embaldosar 2xn",
    titleEn: "Ways to Tile 2xn",
    summaryEs: "Cuenta recubrimientos con una recurrencia tipo Fibonacci.",
    summaryEn: "Counts tilings with a Fibonacci-like recurrence.",
    tagsEs: ["tiling", "domino", "conteo"],
    tagsEn: ["tiling", "domino", "counting"],
    sourceCodeEs: code(
      "waysToTile2xN(n) BEGIN",
      "    IF (n <= 2) THEN BEGIN",
      "        RETURN n;",
      "    END",
      "    RETURN waysToTile2xN(n - 1) + waysToTile2xN(n - 2);",
      "END",
    ),
  }),
];

const dpTopDownExamples: ExampleCatalogItem[] = [
  createExample({
    id: "fibonacci-memoizado",
    slug: "fibonacci-memoizado",
    category: "dp_top_down",
    family: "secuencias",
    difficulty: "basico",
    techniqueBadges: ["PD-TD", "MEMO"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Fibonacci memoizado",
    titleEn: "Memoized Fibonacci",
    summaryEs: "Evita recomputar estados con memoización explícita.",
    summaryEn: "Avoids recomputing states with explicit memoization.",
    tagsEs: ["dp", "memo", "fibonacci"],
    tagsEn: ["dp", "memo", "fibonacci"],
    sourceCodeEs: code(
      "fibonacciMemo(n, memo[n]) BEGIN",
      "    IF (n <= 1) THEN BEGIN",
      "        RETURN n;",
      "    END",
      "    IF (memo[n] != -1) THEN BEGIN",
      "        RETURN memo[n];",
      "    END",
      "    memo[n] <- fibonacciMemo(n - 1, memo) + fibonacciMemo(n - 2, memo);",
      "    RETURN memo[n];",
      "END",
    ),
  }),
  createExample({
    id: "coin-change-top-down",
    slug: "coin-change-top-down",
    category: "dp_top_down",
    family: "numerico",
    difficulty: "intermedio",
    techniqueBadges: ["PD-TD", "MEMO"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Coin Change top-down",
    titleEn: "Coin Change top-down",
    summaryEs: "Memoiza combinaciones por índice y monto.",
    summaryEn: "Memoizes combinations by index and amount.",
    tagsEs: ["dp", "monedas", "memo"],
    tagsEn: ["dp", "coins", "memo"],
    sourceCodeEs: code(
      "coinChangeTopDown(coins[m], amount, i, memo[m][amount]) BEGIN",
      "    IF (amount = 0) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    IF (amount < 0 OR i > m) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    IF (memo[i][amount] != -1) THEN BEGIN",
      "        RETURN memo[i][amount];",
      "    END",
      "    usar <- coinChangeTopDown(coins, amount - coins[i], i, memo);",
      "    saltar <- coinChangeTopDown(coins, amount, i + 1, memo);",
      "    memo[i][amount] <- usar + saltar;",
      "    RETURN memo[i][amount];",
      "END",
    ),
  }),
  createExample({
    id: "knapsack-top-down",
    slug: "knapsack-top-down",
    category: "dp_top_down",
    family: "numerico",
    difficulty: "intermedio",
    techniqueBadges: ["PD-TD", "MEMO", "OPTIMIZATION"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Knapsack top-down",
    titleEn: "Knapsack top-down",
    summaryEs: "Maximiza valor con memoización por índice y capacidad.",
    summaryEn: "Maximizes value with memoization by index and capacity.",
    tagsEs: ["dp", "knapsack", "optimización"],
    tagsEn: ["dp", "knapsack", "optimization"],
    sourceCodeEs: code(
      "knapsackTopDown(W[n], V[n], i, capacidad, memo[n][capacidad]) BEGIN",
      "    IF (i > n OR capacidad <= 0) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    IF (memo[i][capacidad] != -1) THEN BEGIN",
      "        RETURN memo[i][capacidad];",
      "    END",
      "    sinItem <- knapsackTopDown(W, V, i + 1, capacidad, memo);",
      "    conItem <- 0;",
      "    IF (W[i] <= capacidad) THEN BEGIN",
      "        conItem <- V[i] + knapsackTopDown(W, V, i + 1, capacidad - W[i], memo);",
      "    END",
      "    IF (conItem > sinItem) THEN BEGIN",
      "        memo[i][capacidad] <- conItem;",
      "    END",
      "    ELSE BEGIN",
      "        memo[i][capacidad] <- sinItem;",
      "    END",
      "    RETURN memo[i][capacidad];",
      "END",
    ),
  }),
  createExample({
    id: "lcs-top-down",
    slug: "lcs-top-down",
    category: "dp_top_down",
    family: "estructuras",
    difficulty: "intermedio",
    techniqueBadges: ["PD-TD", "MEMO"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "LCS top-down",
    titleEn: "LCS top-down",
    summaryEs: "Memoiza la subsecuencia común más larga por pares de índices.",
    summaryEn: "Memoizes the longest common subsequence by index pairs.",
    tagsEs: ["dp", "lcs", "memo"],
    tagsEn: ["dp", "lcs", "memo"],
    sourceCodeEs: code(
      "lcsTopDown(A[n], B[m], i, j, memo[n][m]) BEGIN",
      "    IF (i > n OR j > m) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    IF (memo[i][j] != -1) THEN BEGIN",
      "        RETURN memo[i][j];",
      "    END",
      "    IF (A[i] = B[j]) THEN BEGIN",
      "        memo[i][j] <- 1 + lcsTopDown(A, B, i + 1, j + 1, memo);",
      "        RETURN memo[i][j];",
      "    END",
      "    op1 <- lcsTopDown(A, B, i + 1, j, memo);",
      "    op2 <- lcsTopDown(A, B, i, j + 1, memo);",
      "    IF (op1 > op2) THEN BEGIN",
      "        memo[i][j] <- op1;",
      "    END",
      "    ELSE BEGIN",
      "        memo[i][j] <- op2;",
      "    END",
      "    RETURN memo[i][j];",
      "END",
    ),
  }),
  createExample({
    id: "edit-distance-top-down",
    slug: "edit-distance-top-down",
    category: "dp_top_down",
    family: "estructuras",
    difficulty: "avanzado",
    techniqueBadges: ["PD-TD", "MEMO"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Edit Distance top-down",
    titleEn: "Edit Distance top-down",
    summaryEs: "Memoiza la distancia de edición por posición en dos cadenas.",
    summaryEn: "Memoizes edit distance by positions in two strings.",
    tagsEs: ["dp", "edit distance", "memo"],
    tagsEn: ["dp", "edit distance", "memo"],
    sourceCodeEs: code(
      "editDistanceTopDown(A[n], B[m], i, j, memo[n][m]) BEGIN",
      "    IF (i > n) THEN BEGIN",
      "        RETURN m - j + 1;",
      "    END",
      "    IF (j > m) THEN BEGIN",
      "        RETURN n - i + 1;",
      "    END",
      "    IF (memo[i][j] != -1) THEN BEGIN",
      "        RETURN memo[i][j];",
      "    END",
      "    IF (A[i] = B[j]) THEN BEGIN",
      "        memo[i][j] <- editDistanceTopDown(A, B, i + 1, j + 1, memo);",
      "        RETURN memo[i][j];",
      "    END",
      "    insertar <- editDistanceTopDown(A, B, i, j + 1, memo);",
      "    borrar <- editDistanceTopDown(A, B, i + 1, j, memo);",
      "    reemplazar <- editDistanceTopDown(A, B, i + 1, j + 1, memo);",
      "    memo[i][j] <- 1 + min3(insertar, borrar, reemplazar);",
      "    RETURN memo[i][j];",
      "END",
    ),
  }),
  createExample({
    id: "matrix-chain-top-down",
    slug: "matrix-chain-top-down",
    category: "dp_top_down",
    family: "matrices",
    difficulty: "avanzado",
    techniqueBadges: ["PD-TD", "MEMO", "MATRIX"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Matrix Chain top-down",
    titleEn: "Matrix Chain top-down",
    summaryEs: "Memoiza el costo óptimo de parentización.",
    summaryEn: "Memoizes the optimal parenthesization cost.",
    tagsEs: ["dp", "matrices", "memo"],
    tagsEn: ["dp", "matrices", "memo"],
    sourceCodeEs: code(
      "matrixChainTopDown(P[n], i, j, memo[n][n]) BEGIN",
      "    IF (i = j) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    IF (memo[i][j] != -1) THEN BEGIN",
      "        RETURN memo[i][j];",
      "    END",
      "    mejor <- 999999;",
      "    FOR k <- i TO j - 1 DO BEGIN",
      "        costoIzq <- matrixChainTopDown(P, i, k, memo);",
      "        costoDer <- matrixChainTopDown(P, k + 1, j, memo);",
      "        costo <- costoIzq + costoDer + P[i - 1] * P[k] * P[j];",
      "        IF (costo < mejor) THEN BEGIN",
      "            mejor <- costo;",
      "        END",
      "    END",
      "    memo[i][j] <- mejor;",
      "    RETURN memo[i][j];",
      "END",
    ),
  }),
];

const dpBottomUpExamples: ExampleCatalogItem[] = [
  createExample({
    id: "fibonacci-tabulado",
    slug: "fibonacci-tabulado",
    category: "dp_bottom_up",
    family: "secuencias",
    difficulty: "basico",
    techniqueBadges: ["PD-BU", "TABLE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Fibonacci tabulado",
    titleEn: "Tabulated Fibonacci",
    summaryEs: "Construye la tabla de estados desde los casos base.",
    summaryEn: "Builds the state table from the base cases.",
    tagsEs: ["dp", "tabla", "fibonacci"],
    tagsEn: ["dp", "table", "fibonacci"],
    sourceCodeEs: code(
      "fibonacciTab(n) BEGIN",
      "    dp[0] <- 0;",
      "    dp[1] <- 1;",
      "    FOR i <- 2 TO n DO BEGIN",
      "        dp[i] <- dp[i - 1] + dp[i - 2];",
      "    END",
      "    RETURN dp[n];",
      "END",
    ),
  }),
  createExample({
    id: "coin-change-bottom-up",
    slug: "coin-change-bottom-up",
    category: "dp_bottom_up",
    family: "numerico",
    difficulty: "intermedio",
    techniqueBadges: ["PD-BU", "TABLE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Coin Change bottom-up",
    titleEn: "Coin Change bottom-up",
    summaryEs: "Llena la tabla de combinaciones iterativamente.",
    summaryEn: "Fills the combinations table iteratively.",
    tagsEs: ["dp", "monedas", "tabla"],
    tagsEn: ["dp", "coins", "table"],
    sourceCodeEs: code(
      "coinChangeBottomUp(coins[m], amount) BEGIN",
      "    dp[0] <- 1;",
      "    FOR a <- 1 TO amount DO BEGIN",
      "        dp[a] <- 0;",
      "    END",
      "    FOR i <- 1 TO m DO BEGIN",
      "        FOR a <- coins[i] TO amount DO BEGIN",
      "            dp[a] <- dp[a] + dp[a - coins[i]];",
      "        END",
      "    END",
      "    RETURN dp[amount];",
      "END",
    ),
  }),
  createExample({
    id: "knapsack-bottom-up",
    slug: "knapsack-bottom-up",
    category: "dp_bottom_up",
    family: "numerico",
    difficulty: "intermedio",
    techniqueBadges: ["PD-BU", "TABLE", "OPTIMIZATION"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Knapsack bottom-up",
    titleEn: "Knapsack bottom-up",
    summaryEs: "Construye una matriz de valor óptimo por capacidad.",
    summaryEn: "Builds an optimal-value matrix by capacity.",
    tagsEs: ["dp", "knapsack", "tabla"],
    tagsEn: ["dp", "knapsack", "table"],
    sourceCodeEs: code(
      "knapsackBottomUp(W[n], V[n], n, capacidad) BEGIN",
      "    FOR c <- 0 TO capacidad DO BEGIN",
      "        dp[0][c] <- 0;",
      "    END",
      "    FOR i <- 1 TO n DO BEGIN",
      "        FOR c <- 0 TO capacidad DO BEGIN",
      "            dp[i][c] <- dp[i - 1][c];",
      "            IF (W[i] <= c) THEN BEGIN",
      "                candidato <- dp[i - 1][c - W[i]] + V[i];",
      "                IF (candidato > dp[i][c]) THEN BEGIN",
      "                    dp[i][c] <- candidato;",
      "                END",
      "            END",
      "        END",
      "    END",
      "    RETURN dp[n][capacidad];",
      "END",
    ),
  }),
  createExample({
    id: "lcs-bottom-up",
    slug: "lcs-bottom-up",
    category: "dp_bottom_up",
    family: "estructuras",
    difficulty: "intermedio",
    techniqueBadges: ["PD-BU", "TABLE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "LCS bottom-up",
    titleEn: "LCS bottom-up",
    summaryEs: "Llena la tabla de subsecuencias comunes más largas.",
    summaryEn: "Fills the longest-common-subsequence table.",
    tagsEs: ["dp", "lcs", "tabla"],
    tagsEn: ["dp", "lcs", "table"],
    sourceCodeEs: code(
      "lcsBottomUp(A[n], B[m], n, m) BEGIN",
      "    FOR i <- 0 TO n DO BEGIN",
      "        dp[i][0] <- 0;",
      "    END",
      "    FOR j <- 0 TO m DO BEGIN",
      "        dp[0][j] <- 0;",
      "    END",
      "    FOR i <- 1 TO n DO BEGIN",
      "        FOR j <- 1 TO m DO BEGIN",
      "            IF (A[i] = B[j]) THEN BEGIN",
      "                dp[i][j] <- dp[i - 1][j - 1] + 1;",
      "            END",
      "            ELSE BEGIN",
      "                IF (dp[i - 1][j] > dp[i][j - 1]) THEN BEGIN",
      "                    dp[i][j] <- dp[i - 1][j];",
      "                END",
      "                ELSE BEGIN",
      "                    dp[i][j] <- dp[i][j - 1];",
      "                END",
      "            END",
      "        END",
      "    END",
      "    RETURN dp[n][m];",
      "END",
    ),
  }),
  createExample({
    id: "edit-distance-bottom-up",
    slug: "edit-distance-bottom-up",
    category: "dp_bottom_up",
    family: "estructuras",
    difficulty: "avanzado",
    techniqueBadges: ["PD-BU", "TABLE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Edit Distance bottom-up",
    titleEn: "Edit Distance bottom-up",
    summaryEs: "Construye la distancia mínima por prefijos.",
    summaryEn: "Builds the minimum distance by prefixes.",
    tagsEs: ["dp", "edit distance", "tabla"],
    tagsEn: ["dp", "edit distance", "table"],
    sourceCodeEs: code(
      "editDistanceBottomUp(A[n], B[m], n, m) BEGIN",
      "    FOR i <- 0 TO n DO BEGIN",
      "        dp[i][0] <- i;",
      "    END",
      "    FOR j <- 0 TO m DO BEGIN",
      "        dp[0][j] <- j;",
      "    END",
      "    FOR i <- 1 TO n DO BEGIN",
      "        FOR j <- 1 TO m DO BEGIN",
      "            IF (A[i] = B[j]) THEN BEGIN",
      "                dp[i][j] <- dp[i - 1][j - 1];",
      "            END",
      "            ELSE BEGIN",
      "                dp[i][j] <- 1 + min3(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]);",
      "            END",
      "        END",
      "    END",
      "    RETURN dp[n][m];",
      "END",
    ),
  }),
  createExample({
    id: "matrix-chain-bottom-up",
    slug: "matrix-chain-bottom-up",
    category: "dp_bottom_up",
    family: "matrices",
    difficulty: "avanzado",
    techniqueBadges: ["PD-BU", "TABLE", "MATRIX"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Matrix Chain bottom-up",
    titleEn: "Matrix Chain bottom-up",
    summaryEs: "Calcula el costo óptimo por longitud de cadena.",
    summaryEn: "Computes optimal cost by chain length.",
    tagsEs: ["dp", "matrices", "tabla"],
    tagsEn: ["dp", "matrices", "table"],
    sourceCodeEs: code(
      "matrixChainBottomUp(P[n], n) BEGIN",
      "    FOR i <- 1 TO n DO BEGIN",
      "        dp[i][i] <- 0;",
      "    END",
      "    FOR len <- 2 TO n DO BEGIN",
      "        FOR i <- 1 TO n - len + 1 DO BEGIN",
      "            j <- i + len - 1;",
      "            dp[i][j] <- 999999;",
      "            FOR k <- i TO j - 1 DO BEGIN",
      "                costo <- dp[i][k] + dp[k + 1][j] + P[i - 1] * P[k] * P[j];",
      "                IF (costo < dp[i][j]) THEN BEGIN",
      "                    dp[i][j] <- costo;",
      "                END",
      "            END",
      "        END",
      "    END",
      "    RETURN dp[1][n];",
      "END",
    ),
  }),
  createExample({
    id: "floyd-warshall",
    slug: "floyd-warshall",
    category: "dp_bottom_up",
    family: "matrices",
    difficulty: "avanzado",
    techniqueBadges: ["PD-BU", "GRAPH", "TABLE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Floyd-Warshall",
    titleEn: "Floyd-Warshall",
    summaryEs: "Relaja todas las rutas pasando por vértices intermedios.",
    summaryEn: "Relaxes all paths through intermediate vertices.",
    tagsEs: ["dp", "grafos", "caminos"],
    tagsEn: ["dp", "graphs", "paths"],
    sourceCodeEs: code(
      "floydWarshall(D[n][n], n) BEGIN",
      "    FOR k <- 1 TO n DO BEGIN",
      "        FOR i <- 1 TO n DO BEGIN",
      "            FOR j <- 1 TO n DO BEGIN",
      "                IF (D[i][k] + D[k][j] < D[i][j]) THEN BEGIN",
      "                    D[i][j] <- D[i][k] + D[k][j];",
      "                END",
      "            END",
      "        END",
      "    END",
      "    RETURN 0;",
      "END",
    ),
  }),
];

const greedyExamples: ExampleCatalogItem[] = [
  createExample({
    id: "activity-selection",
    slug: "activity-selection",
    category: "greedy",
    family: "clasicos",
    difficulty: "basico",
    techniqueBadges: ["GREEDY", "CHOICE", "SCHEDULING"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Activity Selection",
    titleEn: "Activity Selection",
    summaryEs: "Elige actividades por tiempo de finalización.",
    summaryEn: "Chooses activities by finishing time.",
    tagsEs: ["voraz", "actividades", "horarios"],
    tagsEn: ["greedy", "activities", "scheduling"],
    sourceCodeEs: code(
      "activitySelection(ini[n], fin[n], n) BEGIN",
      "    CALL sortByFinishTime(ini, fin, n);",
      "    total <- 1;",
      "    ultimo <- 1;",
      "    FOR i <- 2 TO n DO BEGIN",
      "        IF (ini[i] >= fin[ultimo]) THEN BEGIN",
      "            total <- total + 1;",
      "            ultimo <- i;",
      "        END",
      "    END",
      "    RETURN total;",
      "END",
    ),
  }),
  createExample({
    id: "fractional-knapsack",
    slug: "fractional-knapsack",
    category: "greedy",
    family: "numerico",
    difficulty: "intermedio",
    techniqueBadges: ["GREEDY", "RATIO", "CHOICE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Fractional Knapsack",
    titleEn: "Fractional Knapsack",
    summaryEs: "Toma primero la mejor relación valor/peso.",
    summaryEn: "Takes the best value-to-weight ratio first.",
    tagsEs: ["voraz", "ratio", "mochila"],
    tagsEn: ["greedy", "ratio", "knapsack"],
    sourceCodeEs: code(
      "fractionalKnapsack(W[n], V[n], n, capacidad) BEGIN",
      "    CALL sortByRatioDescending(W, V, n);",
      "    total <- 0;",
      "    restante <- capacidad;",
      "    FOR i <- 1 TO n DO BEGIN",
      "        IF (W[i] <= restante) THEN BEGIN",
      "            total <- total + V[i];",
      "            restante <- restante - W[i];",
      "        END",
      "        ELSE BEGIN",
      "            total <- total + V[i] * restante / W[i];",
      "            RETURN total;",
      "        END",
      "    END",
      "    RETURN total;",
      "END",
    ),
  }),
  createExample({
    id: "huffman-coding",
    slug: "huffman-coding",
    category: "greedy",
    family: "estructuras",
    difficulty: "intermedio",
    techniqueBadges: ["GREEDY", "PRIORITY", "TREE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Huffman Coding",
    titleEn: "Huffman Coding",
    summaryEs: "Fusiona repetidamente los pesos mínimos.",
    summaryEn: "Repeatedly merges the smallest weights.",
    tagsEs: ["voraz", "cola mínima", "árbol"],
    tagsEn: ["greedy", "min queue", "tree"],
    sourceCodeEs: code(
      "huffman(W[n], n) BEGIN",
      "    CALL buildMinQueue(W, n);",
      "    total <- 0;",
      "    FOR i <- 1 TO n - 1 DO BEGIN",
      "        a <- extractMin(W);",
      "        b <- extractMin(W);",
      "        c <- a + b;",
      "        total <- total + c;",
      "        CALL insertMin(W, c);",
      "    END",
      "    RETURN total;",
      "END",
    ),
  }),
  createExample({
    id: "kruskal",
    slug: "kruskal",
    category: "greedy",
    family: "estructuras",
    difficulty: "intermedio",
    techniqueBadges: ["GREEDY", "MST", "GRAPH"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Kruskal",
    titleEn: "Kruskal",
    summaryEs: "Añade la arista segura más liviana disponible.",
    summaryEn: "Adds the lightest safe edge available.",
    tagsEs: ["voraz", "mst", "grafos"],
    tagsEn: ["greedy", "mst", "graphs"],
    sourceCodeEs: code(
      "kruskal(U[m], V[m], W[m], m, n) BEGIN",
      "    CALL sortEdgesByWeight(U, V, W, m);",
      "    CALL makeSets(n);",
      "    total <- 0;",
      "    edges <- 0;",
      "    FOR i <- 1 TO m DO BEGIN",
      "        IF (findSet(U[i]) != findSet(V[i])) THEN BEGIN",
      "            CALL unionSet(U[i], V[i]);",
      "            total <- total + W[i];",
      "            edges <- edges + 1;",
      "        END",
      "    END",
      "    RETURN total;",
      "END",
    ),
  }),
  createExample({
    id: "prim",
    slug: "prim",
    category: "greedy",
    family: "estructuras",
    difficulty: "intermedio",
    techniqueBadges: ["GREEDY", "MST", "GRAPH"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Prim",
    titleEn: "Prim",
    summaryEs: "Expande el árbol con la mejor arista hacia afuera.",
    summaryEn: "Expands the tree with the best outward edge.",
    tagsEs: ["voraz", "mst", "grafos"],
    tagsEn: ["greedy", "mst", "graphs"],
    sourceCodeEs: code(
      "prim(G[n][n], n) BEGIN",
      "    FOR i <- 1 TO n DO BEGIN",
      "        key[i] <- 999999;",
      "        used[i] <- false;",
      "    END",
      "    key[1] <- 0;",
      "    total <- 0;",
      "    FOR count <- 1 TO n DO BEGIN",
      "        u <- minKey(key, used, n);",
      "        used[u] <- true;",
      "        total <- total + key[u];",
      "        FOR v <- 1 TO n DO BEGIN",
      "            IF (used[v] = false AND G[u][v] < key[v]) THEN BEGIN",
      "                key[v] <- G[u][v];",
      "            END",
      "        END",
      "    END",
      "    RETURN total;",
      "END",
    ),
  }),
  createExample({
    id: "dijkstra",
    slug: "dijkstra",
    category: "greedy",
    family: "estructuras",
    difficulty: "intermedio",
    techniqueBadges: ["GREEDY", "SHORTEST_PATH", "GRAPH"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Dijkstra",
    titleEn: "Dijkstra",
    summaryEs: "Fija vértices por distancia mínima conocida.",
    summaryEn: "Locks vertices by the smallest known distance.",
    tagsEs: ["voraz", "caminos mínimos", "grafos"],
    tagsEn: ["greedy", "shortest path", "graphs"],
    sourceCodeEs: code(
      "dijkstra(G[n][n], n, source) BEGIN",
      "    FOR i <- 1 TO n DO BEGIN",
      "        dist[i] <- 999999;",
      "        used[i] <- false;",
      "    END",
      "    dist[source] <- 0;",
      "    FOR count <- 1 TO n DO BEGIN",
      "        u <- minDistance(dist, used, n);",
      "        used[u] <- true;",
      "        FOR v <- 1 TO n DO BEGIN",
      "            IF (used[v] = false AND dist[u] + G[u][v] < dist[v]) THEN BEGIN",
      "                dist[v] <- dist[u] + G[u][v];",
      "            END",
      "        END",
      "    END",
      "    RETURN 0;",
      "END",
    ),
  }),
];

const backtrackingExamples: ExampleCatalogItem[] = [
  createExample({
    id: "n-queens",
    slug: "n-queens",
    category: "backtracking",
    family: "clasicos",
    difficulty: "intermedio",
    techniqueBadges: ["BT", "UNDO", "CHOICE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "N-Queens",
    titleEn: "N-Queens",
    summaryEs: "Prueba posiciones y deshace al volver.",
    summaryEn: "Tries positions and undoes them on return.",
    tagsEs: ["backtracking", "reinas", "undo"],
    tagsEn: ["backtracking", "queens", "undo"],
    sourceCodeEs: code(
      "nQueens(Q[n], row, n) BEGIN",
      "    IF (row > n) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    total <- 0;",
      "    FOR col <- 1 TO n DO BEGIN",
      "        IF (isSafeQueen(Q, row, col) = true) THEN BEGIN",
      "            Q[row] <- col;",
      "            total <- total + nQueens(Q, row + 1, n);",
      "            Q[row] <- 0;",
      "        END",
      "    END",
      "    RETURN total;",
      "END",
    ),
  }),
  createExample({
    id: "sudoku-solver",
    slug: "sudoku-solver",
    category: "backtracking",
    family: "clasicos",
    difficulty: "avanzado",
    techniqueBadges: ["BT", "UNDO", "GRID"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Sudoku Solver",
    titleEn: "Sudoku Solver",
    summaryEs: "Explora números válidos y deshace cuando falla.",
    summaryEn: "Explores valid numbers and undoes them on failure.",
    tagsEs: ["backtracking", "sudoku", "grid"],
    tagsEn: ["backtracking", "sudoku", "grid"],
    sourceCodeEs: code(
      "sudokuSolver(B[9][9], cell) BEGIN",
      "    IF (cell > 81) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    fila <- ((cell - 1) DIV 9) + 1;",
      "    col <- ((cell - 1) MOD 9) + 1;",
      "    IF (B[fila][col] != 0) THEN BEGIN",
      "        RETURN sudokuSolver(B, cell + 1);",
      "    END",
      "    FOR num <- 1 TO 9 DO BEGIN",
      "        IF (isValidSudoku(B, fila, col, num) = true) THEN BEGIN",
      "            B[fila][col] <- num;",
      "            ok <- sudokuSolver(B, cell + 1);",
      "            IF (ok = 1) THEN BEGIN",
      "                RETURN 1;",
      "            END",
      "            B[fila][col] <- 0;",
      "        END",
      "    END",
      "    RETURN 0;",
      "END",
    ),
  }),
  createExample({
    id: "subset-sum",
    slug: "subset-sum",
    category: "backtracking",
    family: "numerico",
    difficulty: "intermedio",
    techniqueBadges: ["BT", "CHOICE", "UNDO"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Subset Sum",
    titleEn: "Subset Sum",
    summaryEs: "Elige o descarta cada elemento recursivamente.",
    summaryEn: "Chooses or skips each element recursively.",
    tagsEs: ["backtracking", "subset", "decisión"],
    tagsEn: ["backtracking", "subset", "choice"],
    sourceCodeEs: code(
      "subsetSum(A[n], i, n, actual, objetivo) BEGIN",
      "    IF (actual = objetivo) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    IF (i > n OR actual > objetivo) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    elegido[i] <- true;",
      "    conItem <- subsetSum(A, i + 1, n, actual + A[i], objetivo);",
      "    elegido[i] <- false;",
      "    sinItem <- subsetSum(A, i + 1, n, actual, objetivo);",
      "    RETURN conItem + sinItem;",
      "END",
    ),
  }),
  createExample({
    id: "permutations",
    slug: "permutations",
    category: "backtracking",
    family: "estructuras",
    difficulty: "intermedio",
    techniqueBadges: ["BT", "UNDO", "CHOICE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Permutations",
    titleEn: "Permutations",
    summaryEs: "Intercambia opciones, explora y deshace.",
    summaryEn: "Swaps choices, explores, and undoes.",
    tagsEs: ["backtracking", "permutaciones", "swap"],
    tagsEn: ["backtracking", "permutations", "swap"],
    sourceCodeEs: code(
      "permutations(A[n], pos, n) BEGIN",
      "    IF (pos > n) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    total <- 0;",
      "    FOR i <- pos TO n DO BEGIN",
      "        temp <- A[pos];",
      "        A[pos] <- A[i];",
      "        A[i] <- temp;",
      "        total <- total + permutations(A, pos + 1, n);",
      "        temp <- A[pos];",
      "        A[pos] <- A[i];",
      "        A[i] <- temp;",
      "    END",
      "    RETURN total;",
      "END",
    ),
  }),
  createExample({
    id: "maze-solver",
    slug: "maze-solver",
    category: "backtracking",
    family: "estructuras",
    difficulty: "intermedio",
    techniqueBadges: ["BT", "GRID", "UNDO"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Maze Solver",
    titleEn: "Maze Solver",
    summaryEs: "Marca la celda actual, explora vecinos y desmarca.",
    summaryEn: "Marks the current cell, explores neighbors, and unmarks.",
    tagsEs: ["backtracking", "laberinto", "grid"],
    tagsEn: ["backtracking", "maze", "grid"],
    sourceCodeEs: code(
      "mazeSolver(M[n][n], fila, col, n) BEGIN",
      "    IF (fila < 1 OR col < 1 OR fila > n OR col > n) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    IF (M[fila][col] != 0) THEN BEGIN",
      "        RETURN 0;",
      "    END",
      "    IF (fila = n AND col = n) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    M[fila][col] <- 2;",
      "    total <- 0;",
      "    total <- total + mazeSolver(M, fila + 1, col, n);",
      "    total <- total + mazeSolver(M, fila - 1, col, n);",
      "    total <- total + mazeSolver(M, fila, col + 1, n);",
      "    total <- total + mazeSolver(M, fila, col - 1, n);",
      "    M[fila][col] <- 0;",
      "    RETURN total;",
      "END",
    ),
  }),
  createExample({
    id: "graph-coloring",
    slug: "graph-coloring",
    category: "backtracking",
    family: "estructuras",
    difficulty: "avanzado",
    techniqueBadges: ["BT", "GRAPH", "UNDO"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Graph Coloring",
    titleEn: "Graph Coloring",
    summaryEs: "Prueba colores válidos y deshace al retroceder.",
    summaryEn: "Tries valid colors and undoes them when backtracking.",
    tagsEs: ["backtracking", "grafos", "coloreo"],
    tagsEn: ["backtracking", "graphs", "coloring"],
    sourceCodeEs: code(
      "graphColoring(G[n][n], color[n], v, n, k) BEGIN",
      "    IF (v > n) THEN BEGIN",
      "        RETURN 1;",
      "    END",
      "    total <- 0;",
      "    FOR c <- 1 TO k DO BEGIN",
      "        IF (isSafeColor(G, color, v, c, n) = true) THEN BEGIN",
      "            color[v] <- c;",
      "            total <- total + graphColoring(G, color, v + 1, n, k);",
      "            color[v] <- 0;",
      "        END",
      "    END",
      "    RETURN total;",
      "END",
    ),
  }),
];

const branchAndBoundExamples: ExampleCatalogItem[] = [
  createExample({
    id: "knapsack-branch-and-bound",
    slug: "knapsack-branch-and-bound",
    category: "branch_and_bound",
    family: "numerico",
    difficulty: "avanzado",
    techniqueBadges: ["B&B", "BOUND", "PRUNE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Knapsack B&B",
    titleEn: "Knapsack B&B",
    summaryEs: "Usa una cota superior para podar ramas.",
    summaryEn: "Uses an upper bound to prune branches.",
    tagsEs: ["branch and bound", "knapsack", "poda"],
    tagsEn: ["branch and bound", "knapsack", "prune"],
    catalogTier: "blocked",
    sourceCodeEs: code(
      "knapsackBB(W[n], V[n], i, n, peso, valor, capacidad, mejor) BEGIN",
      "    IF (peso > capacidad) THEN BEGIN",
      "        RETURN mejor;",
      "    END",
      "    IF (valor > mejor) THEN BEGIN",
      "        mejor <- valor;",
      "    END",
      "    cota <- estimateKnapsackBound(W, V, i, n, peso, valor, capacidad);",
      "    IF (cota <= mejor) THEN BEGIN",
      "        RETURN mejor;",
      "    END",
      "    IF (i > n) THEN BEGIN",
      "        RETURN mejor;",
      "    END",
      "    mejor <- knapsackBB(W, V, i + 1, n, peso + W[i], valor + V[i], capacidad, mejor);",
      "    mejor <- knapsackBB(W, V, i + 1, n, peso, valor, capacidad, mejor);",
      "    RETURN mejor;",
      "END",
      "",
      "estimateKnapsackBound(W, V, i, n, peso, valor, capacidad) BEGIN",
      "    RETURN 0;",
      "END",
    ),
  }),
  createExample({
    id: "traveling-salesman-branch-and-bound",
    slug: "traveling-salesman-branch-and-bound",
    category: "branch_and_bound",
    family: "estructuras",
    difficulty: "avanzado",
    techniqueBadges: ["B&B", "BOUND", "PRUNE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Traveling Salesman B&B",
    titleEn: "Traveling Salesman B&B",
    summaryEs: "Poda recorridos usando una cota de costo.",
    summaryEn: "Prunes tours using a cost bound.",
    tagsEs: ["branch and bound", "tsp", "cota"],
    tagsEn: ["branch and bound", "tsp", "bound"],
    catalogTier: "blocked",
    sourceCodeEs: code(
      "tspBB(C[n][n], ciudad, visitados, costo, n, mejor) BEGIN",
      "    IF (visitados = n) THEN BEGIN",
      "        total <- costo + C[ciudad][1];",
      "        IF (total < mejor) THEN BEGIN",
      "            mejor <- total;",
      "        END",
      "        RETURN mejor;",
      "    END",
      "    cota <- estimateTspBound(C, ciudad, visitados, costo, n);",
      "    IF (cota >= mejor) THEN BEGIN",
      "        RETURN mejor;",
      "    END",
      "    FOR sig <- 1 TO n DO BEGIN",
      "        IF (visited[sig] = false) THEN BEGIN",
      "            visited[sig] <- true;",
      "            mejor <- tspBB(C, sig, visitados + 1, costo + C[ciudad][sig], n, mejor);",
      "            visited[sig] <- false;",
      "        END",
      "    END",
      "    RETURN mejor;",
      "END",
      "",
      "estimateTspBound(C, ciudad, visitados, costo, n) BEGIN",
      "    RETURN 0;",
      "END",
    ),
  }),
  createExample({
    id: "assignment-problem-branch-and-bound",
    slug: "assignment-problem-branch-and-bound",
    category: "branch_and_bound",
    family: "estructuras",
    difficulty: "avanzado",
    techniqueBadges: ["B&B", "BOUND", "OPTIMIZATION"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Assignment Problem B&B",
    titleEn: "Assignment Problem B&B",
    summaryEs: "Explora asignaciones con cota inferior.",
    summaryEn: "Explores assignments with a lower bound.",
    tagsEs: ["branch and bound", "asignación", "cota"],
    tagsEn: ["branch and bound", "assignment", "bound"],
    catalogTier: "blocked",
    sourceCodeEs: code(
      "assignmentBB(C[n][n], worker, n, costo, mejor) BEGIN",
      "    IF (worker > n) THEN BEGIN",
      "        IF (costo < mejor) THEN BEGIN",
      "            mejor <- costo;",
      "        END",
      "        RETURN mejor;",
      "    END",
      "    cota <- estimateAssignmentBound(C, worker, n, costo);",
      "    IF (cota >= mejor) THEN BEGIN",
      "        RETURN mejor;",
      "    END",
      "    FOR job <- 1 TO n DO BEGIN",
      "        IF (assigned[job] = false) THEN BEGIN",
      "            assigned[job] <- true;",
      "            mejor <- assignmentBB(C, worker + 1, n, costo + C[worker][job], mejor);",
      "            assigned[job] <- false;",
      "        END",
      "    END",
      "    RETURN mejor;",
      "END",
      "",
      "estimateAssignmentBound(C, worker, n, costo) BEGIN",
      "    RETURN 0;",
      "END",
    ),
  }),
  createExample({
    id: "job-scheduling-branch-and-bound",
    slug: "job-scheduling-branch-and-bound",
    category: "branch_and_bound",
    family: "clasicos",
    difficulty: "avanzado",
    techniqueBadges: ["B&B", "BOUND", "SCHEDULING"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Job Scheduling B&B",
    titleEn: "Job Scheduling B&B",
    summaryEs: "Usa una cota para podar asignaciones a máquinas.",
    summaryEn: "Uses a bound to prune machine assignments.",
    tagsEs: ["branch and bound", "scheduling", "poda"],
    tagsEn: ["branch and bound", "scheduling", "prune"],
    catalogTier: "blocked",
    sourceCodeEs: code(
      "jobSchedulingBB(tiempos[n], job, n, cargaActual, mejor) BEGIN",
      "    IF (job > n) THEN BEGIN",
      "        IF (cargaActual < mejor) THEN BEGIN",
      "            mejor <- cargaActual;",
      "        END",
      "        RETURN mejor;",
      "    END",
      "    cota <- estimateScheduleBound(tiempos, job, n, cargaActual);",
      "    IF (cota >= mejor) THEN BEGIN",
      "        RETURN mejor;",
      "    END",
      "    FOR machine <- 1 TO 2 DO BEGIN",
      "        carga[machine] <- carga[machine] + tiempos[job];",
      "        nuevaCarga <- max2(carga[1], carga[2]);",
      "        mejor <- jobSchedulingBB(tiempos, job + 1, n, nuevaCarga, mejor);",
      "        carga[machine] <- carga[machine] - tiempos[job];",
      "    END",
      "    RETURN mejor;",
      "END",
      "",
      "estimateScheduleBound(tiempos, job, n, cargaActual) BEGIN",
      "    RETURN 0;",
      "END",
    ),
  }),
  createExample({
    id: "n-queens-branch-and-bound",
    slug: "n-queens-branch-and-bound",
    category: "branch_and_bound",
    family: "clasicos",
    difficulty: "avanzado",
    techniqueBadges: ["B&B", "BOUND", "PRUNE"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "N-Queens B&B",
    titleEn: "N-Queens B&B",
    summaryEs: "Poda configuraciones con una cota de factibilidad.",
    summaryEn: "Prunes configurations with a feasibility bound.",
    tagsEs: ["branch and bound", "reinas", "poda"],
    tagsEn: ["branch and bound", "queens", "prune"],
    catalogTier: "blocked",
    sourceCodeEs: code(
      "nQueensBB(Q[n], row, n, mejor) BEGIN",
      "    IF (row > n) THEN BEGIN",
      "        mejor <- mejor + 1;",
      "        RETURN mejor;",
      "    END",
      "    cota <- estimateQueensBound(Q, row, n);",
      "    IF (cota = 0) THEN BEGIN",
      "        RETURN mejor;",
      "    END",
      "    FOR col <- 1 TO n DO BEGIN",
      "        IF (isSafeQueen(Q, row, col) = true) THEN BEGIN",
      "            Q[row] <- col;",
      "            mejor <- nQueensBB(Q, row + 1, n, mejor);",
      "            Q[row] <- 0;",
      "        END",
      "    END",
      "    RETURN mejor;",
      "END",
      "",
      "estimateQueensBound(Q, row, n) BEGIN",
      "    RETURN 0;",
      "END",
      "",
      "isSafeQueen(Q, row, col) BEGIN",
      "    RETURN 1;",
      "END",
    ),
  }),
  createExample({
    id: "least-cost-path-branch-and-bound",
    slug: "least-cost-path-branch-and-bound",
    category: "branch_and_bound",
    family: "estructuras",
    difficulty: "avanzado",
    techniqueBadges: ["B&B", "BOUND", "SHORTEST_PATH"],
    verifiedMethods: [],
    enabled: true,
    titleEs: "Least Cost Path B&B",
    titleEn: "Least Cost Path B&B",
    summaryEs: "Poda caminos con una cota inferior de costo.",
    summaryEn: "Prunes paths with a lower cost bound.",
    tagsEs: ["branch and bound", "camino", "cota"],
    tagsEn: ["branch and bound", "path", "bound"],
    catalogTier: "blocked",
    sourceCodeEs: code(
      "leastCostPathBB(G[n][n], actual, destino, costo, mejor, n) BEGIN",
      "    IF (actual = destino) THEN BEGIN",
      "        IF (costo < mejor) THEN BEGIN",
      "            mejor <- costo;",
      "        END",
      "        RETURN mejor;",
      "    END",
      "    cota <- estimatePathBound(G, actual, destino, costo, n);",
      "    IF (cota >= mejor) THEN BEGIN",
      "        RETURN mejor;",
      "    END",
      "    FOR v <- 1 TO n DO BEGIN",
      "        IF (visited[v] = false AND G[actual][v] > 0) THEN BEGIN",
      "            visited[v] <- true;",
      "            mejor <- leastCostPathBB(G, v, destino, costo + G[actual][v], mejor, n);",
      "            visited[v] <- false;",
      "        END",
      "    END",
      "    RETURN mejor;",
      "END",
      "",
      "estimatePathBound(G, actual, destino, costo, n) BEGIN",
      "    RETURN 0;",
      "END",
    ),
  }),
];

export const examplesCatalog: ExampleCatalogItem[] = [
  ...iterativeExamples,
  ...divideAndConquerExamples,
  ...pedagogyExamples,
  ...decreaseAndConquerExamples,
  ...decreaseAndGetConqueredExamples,
  ...dpTopDownExamples,
  ...dpBottomUpExamples,
  ...greedyExamples,
  ...backtrackingExamples,
  ...branchAndBoundExamples,
];

export const getExampleCategoryPage = (category: ExampleCategory): number =>
  EXAMPLE_CATEGORY_META[category].pageIndex;

export const getExampleCategoriesByPage = (page: number): ExampleCategory[] => {
  const safePage = page >= 1 && page <= EXAMPLE_CATEGORY_PAGE_COUNT ? page : 1;

  return EXAMPLE_CATEGORY_ORDER.filter(
    (category) => EXAMPLE_CATEGORY_META[category].pageIndex === safePage,
  );
};

export const isRecursiveCategory = (category: ExampleCategory): boolean =>
  category !== "iterative" &&
  category !== "dp_bottom_up" &&
  category !== "greedy";

export const isExampleCategory = (value: string): value is ExampleCategory =>
  EXAMPLE_CATEGORY_ORDER.includes(value as ExampleCategory);

export const getCategoryBySlug = (slug: string): ExampleCategory | undefined =>
  EXAMPLE_CATEGORY_ORDER.find(
    (category) => EXAMPLE_CATEGORY_META[category].slug === slug,
  );

export const isExampleCategorySlug = (slug: string): boolean =>
  Boolean(getCategoryBySlug(slug));

const normalize = (value: string): string =>
  value
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .trim();

export const sortByLocalizedTitle = (
  items: ExampleCatalogItem[],
  locale: ExampleLocale,
): ExampleCatalogItem[] =>
  [...items].sort((left, right) =>
    left.copy[locale].title.localeCompare(right.copy[locale].title, locale),
  );

export const getEnabledExamples = (
  items: ExampleCatalogItem[] = examplesCatalog,
): ExampleCatalogItem[] => items.filter((item) => item.enabled);

export const getExamplesByCategory = (
  category: ExampleCategory,
  options?: { enabledOnly?: boolean; locale?: ExampleLocale },
): ExampleCatalogItem[] => {
  const enabledOnly = options?.enabledOnly ?? true;
  const locale = options?.locale ?? "es";
  const subset = examplesCatalog.filter(
    (item) => item.category === category && (!enabledOnly || item.enabled),
  );
  return sortByLocalizedTitle(subset, locale);
};

export const categoryHasRecursiveMethods = (
  category: ExampleCategory,
): boolean =>
  getExamplesByCategory(category, { enabledOnly: true }).some(
    (item) => item.verifiedMethods.length > 0,
  );

export const filterByMethods = (
  items: ExampleCatalogItem[],
  methods: RecursiveMethodBadge[],
): ExampleCatalogItem[] => {
  if (methods.length === 0) return items;

  return items.filter(
    (item) =>
      item.verifiedMethods.length > 0 &&
      item.verifiedMethods.some((method) => methods.includes(method)),
  );
};

export const filterByTechniqueBadges = (
  items: ExampleCatalogItem[],
  badges: TechniqueBadge[],
): ExampleCatalogItem[] => {
  if (badges.length === 0) return items;

  return items.filter((item) =>
    item.techniqueBadges.some((badge) => badges.includes(badge)),
  );
};

export const searchExamples = (
  items: ExampleCatalogItem[],
  locale: ExampleLocale,
  query: string,
): ExampleCatalogItem[] => {
  const normalizedQuery = normalize(query);
  if (!normalizedQuery) {
    return items;
  }

  return items.filter((item) => {
    const copy = item.copy[locale];
    const haystack = [copy.title, copy.summary, ...copy.tags]
      .map(normalize)
      .join(" ");

    return haystack.includes(normalizedQuery);
  });
};

export const getCategoryMeta = (
  category: ExampleCategory,
): ExampleCategoryMeta => EXAMPLE_CATEGORY_META[category];

export const getLocalizedExampleSource = (
  example: ExampleCatalogItem,
  locale: ExampleLocale,
): string => example.sourceCodeByLocale[locale];

export const findExampleBySlug = (
  slug: string,
): ExampleCatalogItem | undefined =>
  examplesCatalog.find((item) => item.slug === slug);

export const getMethodTranslationKey = (method: RecursiveMethodBadge): string =>
  EXAMPLE_METHOD_TRANSLATION_KEYS[method];
