import type { SnippetDefinition } from "./snippetCatalog";

export const snippetTemplates: SnippetDefinition[] = [
  {
    id: "template-binary-search",
    label: "Búsqueda binaria",
    shortLabel: "Binaria",
    category: "templates",
    priority: 980,
    aliases: ["binaria", "binary", "binarysearch", "busqueda"],
    insertKind: "template",
    insertText: [
      "busquedaBinaria(A[n], x, inicio, fin) BEGIN",
      "  IF (inicio > fin) THEN BEGIN",
      "    RETURN -1;",
      "  END",
      "  mitad <- (inicio + fin) DIV 2;",
      "  IF (A[mitad] = x) THEN BEGIN",
      "    RETURN mitad;",
      "  END",
      "  ELSE BEGIN",
      "    IF (x < A[mitad]) THEN BEGIN",
      "      RETURN busquedaBinaria(A, x, inicio, mitad - 1);",
      "    END",
      "    ELSE BEGIN",
      "      RETURN busquedaBinaria(A, x, mitad + 1, fin);",
      "    END",
      "  END",
      "END",
    ].join("\n"),
    placeholders: ["x", "inicio", "fin"],
    documentationShort: "Inserta una plantilla recursiva de búsqueda binaria.",
    documentationPedagogical:
      "Úsala cuando el rango se parte por la mitad en cada paso.",
    preview: "Firma + caso base + mitad + llamadas recursivas",
    contextRules: ["lineStart"],
    requiresSelection: false,
    supportsSelectionWrap: false,
    parserExpectation: "parseable",
    status: "active",
    exampleAlgorithmKind: "recursive",
    supportsAnalyze: true,
    supportsDetectMethods: true,
    expectedUseCase:
      "Práctica de divide y vencerás con búsqueda en arreglo ordenado.",
  },
  {
    id: "template-factorial",
    label: "Factorial",
    shortLabel: "Factorial",
    category: "templates",
    priority: 970,
    aliases: ["factorial", "fact"],
    insertKind: "template",
    insertText: [
      "factorial(n) BEGIN",
      "  IF (n <= 1) THEN BEGIN",
      "    RETURN 1;",
      "  END",
      "  RETURN n * factorial(n - 1);",
      "END",
    ].join("\n"),
    placeholders: ["n"],
    documentationShort: "Inserta una plantilla recursiva lineal de factorial.",
    documentationPedagogical:
      "Úsala para practicar caso base y retorno recursivo simple.",
    preview: "Caso base + retorno n * factorial(n - 1)",
    contextRules: ["lineStart"],
    requiresSelection: false,
    supportsSelectionWrap: false,
    parserExpectation: "parseable",
    status: "active",
    exampleAlgorithmKind: "recursive",
    supportsAnalyze: true,
    supportsDetectMethods: true,
    expectedUseCase: "Introducción a recursión lineal.",
  },
  {
    id: "template-fibonacci",
    label: "Fibonacci",
    shortLabel: "Fibonacci",
    category: "templates",
    priority: 960,
    aliases: ["fibonacci", "fib"],
    insertKind: "template",
    insertText: [
      "fibonacci(n) BEGIN",
      "  IF (n <= 1) THEN BEGIN",
      "    RETURN n;",
      "  END",
      "  RETURN fibonacci(n - 1) + fibonacci(n - 2);",
      "END",
    ].join("\n"),
    placeholders: ["n"],
    documentationShort: "Inserta la versión recursiva clásica de Fibonacci.",
    documentationPedagogical:
      "Úsala para practicar doble rama recursiva y comparación con DP.",
    preview: "Caso base + dos llamadas recursivas",
    contextRules: ["lineStart"],
    requiresSelection: false,
    supportsSelectionWrap: false,
    parserExpectation: "parseable",
    status: "active",
    exampleAlgorithmKind: "recursive",
    supportsAnalyze: true,
    supportsDetectMethods: true,
    expectedUseCase:
      "Práctica de branching recursivo y discusión de memoización.",
  },
  {
    id: "template-merge-sort",
    label: "Merge sort",
    shortLabel: "Merge sort",
    category: "templates",
    priority: 950,
    aliases: ["merge", "mergesort"],
    insertKind: "template",
    insertText: [
      "mergeSort(A[n], izq, der) BEGIN",
      "  IF (izq >= der) THEN BEGIN",
      "    RETURN izq;",
      "  END",
      "  medio <- (izq + der) DIV 2;",
      "  CALL mergeSort(A, izq, medio);",
      "  CALL mergeSort(A, medio + 1, der);",
      "  CALL merge(A, izq, medio, der);",
      "  RETURN medio;",
      "END",
    ].join("\n"),
    placeholders: ["A[n]", "izq", "der"],
    documentationShort: "Inserta una plantilla base de merge sort.",
    documentationPedagogical:
      "Úsala para practicar divide y vencerás con combinación explícita.",
    preview: "Partición + dos CALL + merge",
    contextRules: ["lineStart"],
    requiresSelection: false,
    supportsSelectionWrap: false,
    parserExpectation: "parseable",
    status: "active",
    exampleAlgorithmKind: "recursive",
    supportsAnalyze: true,
    supportsDetectMethods: true,
    expectedUseCase: "Práctica de recursión divide y vencerás con combinación.",
  },
  {
    id: "template-quicksort",
    label: "Quicksort",
    shortLabel: "Quicksort",
    category: "templates",
    priority: 940,
    aliases: ["quick", "quicksort"],
    insertKind: "template",
    insertText: [
      "quickSort(A[n], izq, der) BEGIN",
      "  IF (izq >= der) THEN BEGIN",
      "    RETURN izq;",
      "  END",
      "  pivote <- partition(A, izq, der);",
      "  CALL quickSort(A, izq, pivote - 1);",
      "  CALL quickSort(A, pivote + 1, der);",
      "  RETURN pivote;",
      "END",
    ].join("\n"),
    placeholders: ["A[n]", "izq", "der"],
    documentationShort: "Inserta una plantilla base de quicksort.",
    documentationPedagogical:
      "Úsala para practicar escritura y análisis parcial de partición recursiva.",
    preview: "partition + dos CALL recursivos",
    contextRules: ["lineStart"],
    requiresSelection: false,
    supportsSelectionWrap: false,
    parserExpectation: "parseable",
    status: "active",
    exampleAlgorithmKind: "recursive",
    supportsAnalyze: true,
    supportsDetectMethods: true,
    expectedUseCase:
      "Práctica de escritura y análisis guiado con cobertura parcial.",
  },
  {
    id: "template-linear-traversal",
    label: "Recorrido lineal",
    shortLabel: "Recorrido",
    category: "templates",
    priority: 930,
    aliases: ["linear", "recorrido", "scan"],
    insertKind: "template",
    insertText: [
      "recorridoLineal(A[n], n) BEGIN",
      "  FOR i <- 1 TO n DO BEGIN",
      "    actual <- A[i];",
      "  END",
      "  RETURN n;",
      "END",
    ].join("\n"),
    placeholders: ["A[n]", "n"],
    documentationShort: "Inserta una plantilla base para recorrer un arreglo.",
    documentationPedagogical:
      "Úsala cuando el algoritmo visita cada posición una vez.",
    preview: "FOR i <- 1 TO n",
    contextRules: ["lineStart"],
    requiresSelection: false,
    supportsSelectionWrap: false,
    parserExpectation: "parseable",
    status: "active",
    exampleAlgorithmKind: "iterative",
    supportsAnalyze: true,
    supportsDetectMethods: false,
    expectedUseCase: "Esqueleto de algoritmos lineales sobre arreglos.",
  },
  {
    id: "template-array-sum",
    label: "Suma de arreglo",
    shortLabel: "Suma arreglo",
    category: "templates",
    priority: 920,
    aliases: ["sumarray", "suma", "arraysum"],
    insertKind: "template",
    insertText: [
      "sumaArreglo(A[n], n) BEGIN",
      "  suma <- 0;",
      "  FOR i <- 1 TO n DO BEGIN",
      "    suma <- suma + A[i];",
      "  END",
      "  RETURN suma;",
      "END",
    ].join("\n"),
    placeholders: ["A[n]", "n"],
    documentationShort:
      "Inserta una plantilla de suma acumulada sobre arreglo.",
    documentationPedagogical:
      "Úsala para practicar acumuladores y recorridos completos.",
    preview: "suma <- suma + A[i]",
    contextRules: ["lineStart"],
    requiresSelection: false,
    supportsSelectionWrap: false,
    parserExpectation: "parseable",
    status: "active",
    exampleAlgorithmKind: "iterative",
    supportsAnalyze: true,
    supportsDetectMethods: false,
    expectedUseCase: "Algoritmos iterativos con acumulador.",
  },
  {
    id: "template-memoization-simple",
    label: "Memoización simple",
    shortLabel: "Memo",
    category: "templates",
    priority: 910,
    aliases: ["memo", "memoization"],
    insertKind: "template",
    insertText: [
      "fibonacciMemo(n, memo[n]) BEGIN",
      "  IF (n <= 1) THEN BEGIN",
      "    RETURN n;",
      "  END",
      "  IF (memo[n] != -1) THEN BEGIN",
      "    RETURN memo[n];",
      "  END",
      "  memo[n] <- fibonacciMemo(n - 1, memo) + fibonacciMemo(n - 2, memo);",
      "  RETURN memo[n];",
      "END",
    ].join("\n"),
    placeholders: ["n", "memo[n]"],
    documentationShort: "Inserta una plantilla recursiva con memoización.",
    documentationPedagogical:
      "Úsala cuando quieres recordar resultados ya calculados.",
    preview: "Chequeo de memo + guardado + retorno",
    contextRules: ["lineStart"],
    requiresSelection: false,
    supportsSelectionWrap: false,
    parserExpectation: "parseable",
    status: "active",
    exampleAlgorithmKind: "recursive",
    supportsAnalyze: true,
    supportsDetectMethods: true,
    expectedUseCase: "Práctica de optimización de recursión con caché.",
  },
  {
    id: "template-dp-table",
    label: "Llenado de tabla DP",
    shortLabel: "Tabla DP",
    category: "templates",
    priority: 900,
    aliases: ["dp", "table", "tabulation"],
    insertKind: "template",
    insertText: [
      "dpSimple(n, dp[n]) BEGIN",
      "  dp[0] <- 0;",
      "  dp[1] <- 1;",
      "  FOR i <- 2 TO n DO BEGIN",
      "    dp[i] <- dp[i - 1] + dp[i - 2];",
      "  END",
      "  RETURN dp[n];",
      "END",
    ].join("\n"),
    placeholders: ["n", "dp[n]"],
    documentationShort:
      "Inserta una plantilla base de programación dinámica tabulada.",
    documentationPedagogical:
      "Úsala cuando el resultado se construye desde casos base hacia arriba.",
    preview: "Casos base + FOR + dp[i]",
    contextRules: ["lineStart"],
    requiresSelection: false,
    supportsSelectionWrap: false,
    parserExpectation: "parseable",
    status: "active",
    exampleAlgorithmKind: "iterative",
    supportsAnalyze: true,
    supportsDetectMethods: false,
    expectedUseCase: "Práctica de tabulación bottom-up.",
  },
  {
    id: "template-greedy-selection",
    label: "Selección voraz",
    shortLabel: "Voraz",
    category: "templates",
    priority: 890,
    aliases: ["greedy", "voraz", "selection", "fractional"],
    insertKind: "template",
    insertText: [
      "seleccionVoraz(W[n], V[n], n, capacidad) BEGIN",
      "  CALL sortByRatioDescending(W, V, n);",
      "  total <- 0;",
      "  restante <- capacidad;",
      "  FOR i <- 1 TO n DO BEGIN",
      "    IF (W[i] <= restante) THEN BEGIN",
      "      total <- total + V[i];",
      "      restante <- restante - W[i];",
      "    END",
      "  END",
      "  RETURN total;",
      "END",
    ].join("\n"),
    placeholders: ["W[n]", "V[n]", "n", "capacidad"],
    documentationShort: "Inserta una plantilla base de selección voraz.",
    documentationPedagogical:
      "Úsala cuando eliges la mejor opción local sin retroceder.",
    preview: "Ordenar + elegir + actualizar restante",
    contextRules: ["lineStart"],
    requiresSelection: false,
    supportsSelectionWrap: false,
    parserExpectation: "parseable",
    status: "active",
    exampleAlgorithmKind: "iterative",
    supportsAnalyze: true,
    supportsDetectMethods: false,
    expectedUseCase: "Práctica de algoritmos voraces con decisiones locales.",
  },
  {
    id: "template-backtracking-choice",
    label: "Backtracking con deshacer",
    shortLabel: "Backtracking",
    category: "templates",
    priority: 880,
    aliases: ["backtracking", "undo", "choice", "nqueens"],
    insertKind: "template",
    insertText: [
      "backtrackingChoice(estado[n], pos, n) BEGIN",
      "  IF (pos > n) THEN BEGIN",
      "    RETURN 1;",
      "  END",
      "  total <- 0;",
      "  FOR opcion <- 1 TO n DO BEGIN",
      "    IF (isValidChoice(estado, pos, opcion) = true) THEN BEGIN",
      "      estado[pos] <- opcion;",
      "      total <- total + backtrackingChoice(estado, pos + 1, n);",
      "      estado[pos] <- 0;",
      "    END",
      "  END",
      "  RETURN total;",
      "END",
    ].join("\n"),
    placeholders: ["estado[n]", "pos", "n"],
    documentationShort:
      "Inserta una plantilla base de backtracking con elección y undo.",
    documentationPedagogical:
      "Úsala cuando exploras opciones, recursas y deshaces para probar otras ramas.",
    preview: "Elegir + recursar + deshacer",
    contextRules: ["lineStart"],
    requiresSelection: false,
    supportsSelectionWrap: false,
    parserExpectation: "parseable",
    status: "active",
    exampleAlgorithmKind: "recursive",
    supportsAnalyze: true,
    supportsDetectMethods: false,
    expectedUseCase:
      "Práctica de búsqueda por decisiones con deshacer explícito.",
  },
  {
    id: "template-branch-bound-prune",
    label: "Branch and Bound",
    shortLabel: "B&B",
    category: "templates",
    priority: 870,
    aliases: ["branchandbound", "bnb", "bound", "prune"],
    insertKind: "template",
    insertText: [
      "branchBound(V[n], W[n], i, n, peso, valor, capacidad, mejor) BEGIN",
      "  IF (peso > capacidad) THEN BEGIN",
      "    RETURN mejor;",
      "  END",
      "  IF (valor > mejor) THEN BEGIN",
      "    mejor <- valor;",
      "  END",
      "  cota <- estimateBound(V, W, i, n, peso, valor, capacidad);",
      "  IF (cota <= mejor) THEN BEGIN",
      "    RETURN mejor;",
      "  END",
      "  IF (i > n) THEN BEGIN",
      "    RETURN mejor;",
      "  END",
      "  mejor <- branchBound(V, W, i + 1, n, peso + W[i], valor + V[i], capacidad, mejor);",
      "  mejor <- branchBound(V, W, i + 1, n, peso, valor, capacidad, mejor);",
      "  RETURN mejor;",
      "END",
    ].join("\n"),
    placeholders: [
      "V[n]",
      "W[n]",
      "i",
      "n",
      "peso",
      "valor",
      "capacidad",
      "mejor",
    ],
    documentationShort:
      "Inserta una plantilla base de Branch and Bound con cota y poda.",
    documentationPedagogical:
      "Úsala cuando exploras ramas de optimización y descartas las que no pueden mejorar la mejor solución.",
    preview: "Actualizar mejor + calcular cota + podar",
    contextRules: ["lineStart"],
    requiresSelection: false,
    supportsSelectionWrap: false,
    parserExpectation: "parseable",
    status: "active",
    exampleAlgorithmKind: "recursive",
    supportsAnalyze: true,
    supportsDetectMethods: false,
    expectedUseCase: "Práctica de búsqueda con cotas y poda explícita.",
  },
];
